// Outis-Mneme CodeMirror theme — replaces @codemirror/theme-one-dark.
//
// oneDark's syntax classes are generated by CodeMirror's StyleModule with
// per-instance hashed class names, not stable selectors — there's no CSS
// override that reaches them from outside. The only real fix is swapping
// in our own HighlightStyle, same shape as oneDark's (see
// node_modules/@codemirror/theme-one-dark/dist/index.js), recolored to
// the theme's actual palette: one accent green plus grays, not oneDark's
// five-hue violet/coral/malibu/chalky/cyan spread. See
// OUTIS_MNEME_THEME_SPEC.md for the rest of the design system.
import { EditorView } from '@codemirror/view';
import { HighlightStyle, syntaxHighlighting } from '@codemirror/language';
import { tags } from '@lezer/highlight';

const bg = '#0f1512'; // --color-gray-900
const gutterBg = '#090d0c'; // --color-gray-950
const text = '#d4ede2'; // --color-gray-50
const textDim = '#b9d9cb'; // --color-gray-100
const muted = '#7aab98'; // --color-gray-300
const mutedDark = '#3a5346'; // --color-gray-600 -- comments
const accent = '#2dff8f'; // --color-blue-500 / --color-green-500
const accentSoft = 'rgba(45, 255, 143, 0.16)'; // selection
const accentFaint = 'rgba(45, 255, 143, 0.05)'; // active line
const danger = '#ff4e4e';

export const outisMnemeEditorTheme = /*@__PURE__*/ EditorView.theme(
	{
		'&': { color: text, backgroundColor: bg },
		'.cm-content': { caretColor: accent },
		'.cm-cursor, .cm-dropCursor': { borderLeftColor: accent },
		'&.cm-focused > .cm-scroller > .cm-selectionLayer .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection':
			{ backgroundColor: accentSoft },
		'.cm-panels': { backgroundColor: gutterBg, color: text },
		'.cm-panels.cm-panels-top': { borderBottom: '2px solid black' },
		'.cm-panels.cm-panels-bottom': { borderTop: '2px solid black' },
		'.cm-searchMatch': { backgroundColor: accentSoft, outline: `1px solid ${accent}` },
		'.cm-searchMatch.cm-searchMatch-selected': { backgroundColor: accentSoft },
		'.cm-activeLine': { backgroundColor: accentFaint },
		'.cm-selectionMatch': { backgroundColor: accentFaint },
		'&.cm-focused .cm-matchingBracket, &.cm-focused .cm-nonmatchingBracket': {
			backgroundColor: accentSoft
		},
		'.cm-gutters': { backgroundColor: bg, color: mutedDark, border: 'none' },
		'.cm-activeLineGutter': { backgroundColor: accentFaint },
		'.cm-foldPlaceholder': { backgroundColor: 'transparent', border: 'none', color: muted },
		'.cm-tooltip': { border: `1px solid ${mutedDark}`, backgroundColor: gutterBg },
		'.cm-tooltip .cm-tooltip-arrow:before': {
			borderTopColor: 'transparent',
			borderBottomColor: 'transparent'
		},
		'.cm-tooltip .cm-tooltip-arrow:after': {
			borderTopColor: gutterBg,
			borderBottomColor: gutterBg
		},
		'.cm-tooltip-autocomplete': {
			'& > ul > li[aria-selected]': { backgroundColor: accentFaint, color: text }
		}
	},
	{ dark: true }
);

const outisMnemeHighlightStyle = /*@__PURE__*/ HighlightStyle.define([
	{ tag: tags.keyword, color: accent },
	{
		tag: [tags.name, tags.deleted, tags.character, tags.propertyName, tags.macroName],
		color: text
	},
	{ tag: [tags.function(tags.variableName), tags.labelName], color: textDim },
	{
		tag: [tags.color, tags.constant(tags.name), tags.standard(tags.name)],
		color: muted
	},
	{ tag: [tags.definition(tags.name), tags.separator], color: text },
	{
		tag: [
			tags.typeName,
			tags.className,
			tags.number,
			tags.changed,
			tags.annotation,
			tags.modifier,
			tags.self,
			tags.namespace
		],
		color: muted
	},
	{
		tag: [
			tags.operator,
			tags.operatorKeyword,
			tags.url,
			tags.escape,
			tags.regexp,
			tags.link,
			tags.special(tags.string)
		],
		color: muted
	},
	{ tag: [tags.meta, tags.comment], color: mutedDark },
	{ tag: tags.strong, fontWeight: 'bold' },
	{ tag: tags.emphasis, fontStyle: 'italic' },
	{ tag: tags.strikethrough, textDecoration: 'line-through' },
	{ tag: tags.link, color: muted, textDecoration: 'underline' },
	{ tag: tags.heading, fontWeight: 'bold', color: text },
	{ tag: [tags.atom, tags.bool, tags.special(tags.variableName)], color: muted },
	{ tag: [tags.processingInstruction, tags.string, tags.inserted], color: textDim },
	{ tag: tags.invalid, color: danger }
]);

export const outisMneme = [outisMnemeEditorTheme, syntaxHighlighting(outisMnemeHighlightStyle)];
