version: '3.4'

services:
  w-open-webui:
    container_name: w-open-webui
    image: europe-west3-docker.pkg.dev/w-calderone/w-chat-gpt-2/w-chat-gpt-2:latest
    # volumes:
    #   - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.w-open-webui.rule=Host(`gpt2.webranking.tools`)'
      - 'traefik.http.routers.w-open-webui.entrypoints=websecure'
      - 'traefik.http.routers.w-open-webui.tls.certresolver=myhttpchallenge'
      - 'traefik.port=8080'
    env_file: .env.production
    environment:
      # - 'OLLAMA_BASE_URL=http://ollama:11434'
      - ENABLE_OAUTH_SIGNUP=True
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=True
      - DATABASE_URL=postgresql://postgres:r70T6SyirCeN4fOS@postgres/webui
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - postgres
    networks:
      - chatbot-network
    restart: unless-stopped

  postgres:
    image: postgres:17.5
    container_name: postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT-5432}:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=r70T6SyirCeN4fOS
      - POSTGRES_DB=webui
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chatbot-network

  traefik:
    image: 'traefik:v2.0.0-rc3'
    container_name: 'traefik'
    command:
      #- "--log.level=DEBUG"
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true'
      - '--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web'
      #- "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - '--certificatesresolvers.myhttpchallenge.acme.email=sistemi@webranking.it'
      - '--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
      - '8888:8080'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - chatbot-network

volumes:
  # ollama: {}
  # open-webui: {}
  postgres-data: {}

networks:
  chatbot-network:
    external: true
