services:
  # ollama:
  #   volumes:
  #     - ollama:/root/.ollama
  #   container_name: ollama
  #   pull_policy: always
  #   tty: true
  #   restart: unless-stopped
  #   image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      # args:
      #   OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    # image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - postgres
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      # - 'OLLAMA_BASE_URL=http://ollama:11434'
      - ENABLE_OAUTH_SIGNUP=True
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=True
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - 'WEBUI_SECRET_KEY='
      - OPENAI_API_KEY=
      - DATABASE_URL=postgresql://postgres:password@postgres/webui
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  postgres:
    image: postgres:17.5
    container_name: postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT-5432}:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=webui
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  ollama: {}
  postgres-data: {}
