services:
  grafana:
    image: grafana/otel-lgtm:latest
    container_name: lgtm
    ports:
      - "3000:3000"   # Grafana UI
      - "4317:4317"   # OTLP/gRPC
      - "4318:4318"   # OTLP/HTTP
    restart: unless-stopped


  privatedesk-ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/beko2210/privatedesk-ai:${WEBUI_DOCKER_TAG-main}
    container_name: privatedesk-ai
    volumes:
      - privatedesk-ai:/app/backend/data
    depends_on:
      - grafana
    ports:
      - ${OPEN_WEBUI_PORT-8088}:8080
    environment:
      - ENABLE_OTEL=true
      - ENABLE_OTEL_METRICS=true
      - OTEL_EXPORTER_OTLP_INSECURE=true # Use insecure connection for OTLP, remove in production
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://grafana:4317
      - OTEL_SERVICE_NAME=privatedesk-ai
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  privatedesk-ai: {}
