app = "open-webui-26z5ca"
primary_region = "sin" 

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/health"
    protocol = "http"

[mounts]
  source = "openwebui_data"
  destination = "/app/backend/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048
