import Cog6 from '$lib/components/icons/SettingsSolid.svelte';
import Cloud from '$lib/components/icons/CloudSolid.svelte';
import DocumentChartBar from '$lib/components/icons/DocumentChartBar.svelte';
import Wrench from '$lib/components/icons/WrenchSolid.svelte';
import BookOpen from '$lib/components/icons/BookOpenSolid.svelte';
import GlobeAlt from '$lib/components/icons/GlobeAltSolid.svelte';
import CommandLine from '$lib/components/icons/CommandLineSolidSmall.svelte';
import ChatBubbleOval from '$lib/components/icons/ChatBubbleOvalSolid.svelte';
import Headphone from '$lib/components/icons/HeadphoneSolid.svelte';
import Photo from '$lib/components/icons/PhotoSolidSmall.svelte';
import AdjustmentsHorizontal from '$lib/components/icons/AdjustmentsHorizontalSolid.svelte';
import Database from '$lib/components/icons/DatabaseSolid.svelte';

import SettingsAlt from '$lib/components/icons/SettingsAlt.svelte';
import AppNotification from '$lib/components/icons/AppNotification.svelte';
import Link from '$lib/components/icons/Link.svelte';
import WrenchAlt from '$lib/components/icons/WrenchAlt.svelte';
import Face from '$lib/components/icons/Face.svelte';
import SoundHigh from '$lib/components/icons/SoundHigh.svelte';
import DatabaseSettings from '$lib/components/icons/DatabaseSettings.svelte';
import UserCircle from '$lib/components/icons/UserCircle.svelte';
import InfoCircle from '$lib/components/icons/InfoCircle.svelte';

export const ADMIN_SETTINGS = [
	{
		id: 'general',
		title: 'General',
		route: '/admin/settings/general',
		type: 'admin',
		icon: Cog6,
		keywords: [
			'admin',
			'authentication',
			'channels',
			'community',
			'data',
			'general',
			'language',
			'ldap',
			'reverse proxy',
			'roles',
			'settings',
			'theme',
			'update',
			'users',
			'version',
			'webhook'
		]
	},
	{
		id: 'connections',
		title: 'Connections',
		route: '/admin/settings/connections',
		type: 'admin',
		icon: Cloud,
		keywords: [
			'api',
			'base url',
			'connections',
			'direct connections',
			'key',
			'ollama',
			'openai',
			'proxy'
		]
	},
	{
		id: 'models',
		title: 'Models',
		route: '/admin/settings/models',
		type: 'admin',
		icon: Database,
		keywords: [
			'create',
			'delete',
			'edit',
			'export',
			'gguf',
			'import',
			'modelfile',
			'models',
			'pull'
		]
	},
	{
		id: 'evaluations',
		title: 'Evaluations',
		route: '/admin/settings/evaluations',
		type: 'admin',
		icon: DocumentChartBar,
		keywords: [
			'arena models',
			'arena',
			'evaluations',
			'feedback',
			'leaderboard',
			'preference',
			'rating'
		]
	},
	{
		id: 'tools',
		title: 'External Tools',
		route: '/admin/settings/tools',
		type: 'admin',
		icon: Wrench,
		keywords: [
			'extensions',
			'functions',
			'mcp',
			'openapi',
			'plugins',
			'server',
			'tool servers',
			'tools'
		]
	},
	{
		id: 'documents',
		title: 'Documents',
		route: '/admin/settings/documents',
		type: 'admin',
		icon: BookOpen,
		keywords: [
			'chunk',
			'docling',
			'documents',
			'embedding',
			'files',
			'hybrid search',
			'knowledge',
			'ocr',
			'overlap',
			'pdf',
			'query params',
			'rag',
			'splitter',
			'tika',
			'top k',
			'unstructured',
			'upload',
			'vector db'
		]
	},
	{
		id: 'web',
		title: 'Web Search',
		route: '/admin/settings/web',
		type: 'admin',
		icon: GlobeAlt,
		keywords: [
			'bing',
			'duckduckgo',
			'exa',
			'firecrawl',
			'google',
			'moojeh',
			'perplexity',
			'searxng',
			'serp',
			'serper',
			'serply',
			'tavily',
			'web search',
			'yacy'
		]
	},
	{
		id: 'code-execution',
		title: 'Code Execution',
		route: '/admin/settings/code-execution',
		type: 'admin',
		icon: CommandLine,
		keywords: [
			'code execution',
			'compiler',
			'interpreter',
			'jupyter',
			'python',
			'sandbox',
			'unsafe mode'
		]
	},
	{
		id: 'interface',
		title: 'Interface',
		route: '/admin/settings/interface',
		type: 'admin',
		icon: ChatBubbleOval,
		keywords: [
			'appearance',
			'banners',
			'default models',
			'interface',
			'prompt suggestions',
			'tags',
			'tasks',
			'title generation',
			'ui'
		]
	},
	{
		id: 'audio',
		title: 'Audio',
		route: '/admin/settings/audio',
		type: 'admin',
		icon: Headphone,
		keywords: [
			'audio',
			'azure',
			'deepgram',
			'elevenlabs',
			'openai',
			'speech to text',
			'speech',
			'stt',
			'text to speech',
			'tts',
			'voice',
			'whisper'
		]
	},
	{
		id: 'images',
		title: 'Images',
		route: '/admin/settings/images',
		type: 'admin',
		icon: Photo,
		keywords: [
			'automatic1111',
			'comfyui',
			'dalle',
			'gemini',
			'generation',
			'image generation',
			'image size',
			'images',
			'stable diffusion',
			'steps'
		]
	},
	{
		id: 'pipelines',
		title: 'Pipelines',
		route: '/admin/settings/pipelines',
		type: 'admin',
		icon: AdjustmentsHorizontal,
		keywords: [
			'filters',
			'middleware',
			'pipelines',
			'plugins',
			'valves',
			'workflows'
		]
	},
	{
		id: 'db',
		title: 'Database',
		route: '/admin/settings/db',
		type: 'admin',
		icon: Database,
		keywords: [
			'backup',
			'chats',
			'database',
			'download',
			'export',
			'import',
			'reset',
			'users'
		]
	}
];

export const USER_SETTINGS = [
	{
		id: 'general',
		title: 'General',
		type: 'user',
		icon: SettingsAlt,
		keywords: [
			'advanced parameters',
			'advanced params',
			'advanced',
			'configuration',
			'default parameters',
			'default settings',
			'general settings',
			'general',
			'keep alive',
			'languages',
			'notifications',
			'params',
			'repeat penalty',
			'request mode',
			'stream response',
			'system parameters',
			'system prompt',
			'system settings',
			'temperature',
			'theme',
			'top k',
			'top p',
			'translate',
			'webui settings'
		]
	},
	{
		id: 'interface',
		title: 'Interface',
		type: 'user',
		icon: AppNotification,
		keywords: [
			'allow user location',
			'allow voice interruption in call',
			'always collapse code blocks',
			'always expand details',
			'always on web search',
			'always play notification sound',
			'android',
			'auto chat tags',
			'auto copy response to clipboard',
			'auto title',
			'beta',
			'call',
			'changelog',
			'chat background image',
			'chat bubble ui',
			'chat bubble',
			'chat direction',
			'chat tags',
			'chat ui',
			'copy formatted text',
			'dark mode',
			'default model',
			'design',
			'detect artifacts automatically',
			'display emoji in call',
			'display username',
			'enter key behavior',
			'expand mode',
			'file',
			'floating action buttons',
			'followup autogeneration',
			'full width',
			'fullscreen',
			'haptic feedback',
			'high contrast mode',
			'high contrast',
			'iframe sandbox',
			'image compression',
			'interface customization',
			'interface options',
			'landing page mode',
			'landing page',
			'language',
			'layout',
			'light mode',
			'ltr',
			'notifications',
			'oled',
			'paste large text as file',
			'reset background',
			'response auto copy',
			'rich text input',
			'rtl',
			'scroll behavior',
			'scroll on branch change',
			'select model',
			'settings',
			'show username',
			'stream large chunks',
			'stylized pdf export',
			'temporary chat',
			'text scale',
			'theme',
			'title autogeneration',
			'toast notifications',
			'toast',
			'ui scale',
			'upload background',
			'user interface',
			'user location',
			'vibration',
			'voice control',
			'web search in chat',
			'whats new',
			'widescreen mode',
			'widescreen'
		]
	},
	{
		id: 'connections',
		title: 'Connections',
		type: 'user',
		icon: Link,
		keywords: [
			'add connection',
			'api key',
			'base url',
			'connections',
			'direct connection',
			'manage connections',
			'manage direct connections',
			'ollama',
			'openai',
			'settings'
		]
	},
	{
		id: 'tools',
		title: 'External Tools',
		type: 'user',
		icon: WrenchAlt,
		keywords: [
			'add connection',
			'external tools',
			'manage tool servers',
			'manage tools',
			'mcp',
			'settings',
			'tool servers'
		]
	},
	{
		id: 'personalization',
		title: 'Personalization',
		type: 'user',
		icon: Face,
		keywords: [
			'account preferences',
			'account settings',
			'custom instructions',
			'custom settings',
			'experimental',
			'manage memories',
			'memories',
			'memory',
			'personal settings',
			'personalization',
			'personalize',
			'profile',
			'user preferences'
		]
	},
	{
		id: 'audio',
		title: 'Audio',
		type: 'user',
		icon: SoundHigh,
		keywords: [
			'audio config',
			'audio control',
			'audio features',
			'audio input',
			'audio output',
			'audio playback',
			'audio voice',
			'auto playback response',
			'auto playback',
			'auto send',
			'auto transcribe',
			'instant auto send',
			'kokoro',
			'language',
			'non local voices',
			'playback speed',
			'save settings',
			'set voice',
			'sound settings',
			'speech config',
			'speech playback speed',
			'speech rate',
			'speech recognition',
			'speech settings',
			'speech synthesis',
			'speech to text',
			'stt settings',
			'stt',
			'text to speech',
			'tts settings',
			'tts',
			'voice control',
			'voice options',
			'voice playback',
			'voice recognition',
			'voice speed',
			'voice',
			'volume',
			'whisper'
		]
	},
	{
		id: 'data_controls',
		title: 'Data Controls',
		type: 'user',
		icon: DatabaseSettings,
		keywords: [
			'archive all chats',
			'archive chats',
			'archived chats',
			'archive',
			'chat activity',
			'chat history',
			'chat settings',
			'chats',
			'conversation activity',
			'conversation history',
			'conversations',
			'delete all chats',
			'delete chats',
			'delete',
			'export chats',
			'export',
			'history',
			'import chats',
			'import',
			'message activity',
			'message archive',
			'message history',
			'reset'
		]
	},
	{
		id: 'account',
		title: 'Account',
		type: 'user',
		icon: UserCircle,
		keywords: [
			'account preferences',
			'account settings',
			'api keys',
			'api key',
			'avatar',
			'bio',
			'change password',
			'jwt token',
			'jwt',
			'login',
			'name',
			'new password',
			'notification webhook',
			'password',
			'personal settings',
			'privacy settings',
			'profile avatar',
			'profile details',
			'profile image',
			'profile picture',
			'security settings',
			'security',
			'update account',
			'update password',
			'user account',
			'user data',
			'user preferences',
			'user profile',
			'webhook url',
			'webhook'
		]
	},
	{
		id: 'about',
		title: 'About',
		type: 'user',
		icon: InfoCircle,
		keywords: [
			'about app',
			'about me',
			'about open webui',
			'about page',
			'about us',
			'changelog',
			'check for updates',
			'contact',
			'copyright',
			'details',
			'discord',
			'documentation',
			'github',
			'help',
			'information',
			'license',
			'redistributions',
			'release',
			'see whats new',
			'settings',
			'software info',
			'support',
			'terms and conditions',
			'terms of use',
			'twitter',
			'update info',
			'update',
			'version info',
			'version'
		]
	}
];
