"""Chinese descriptions for the relational database schema."""

from __future__ import annotations

from sqlalchemy import MetaData

TABLE_COMMENTS = {
    'access_grant': '资源访问授权记录',
    'api_key': '用户 API 密钥',
    'auth': '用户登录认证信息',
    'automation': '自动化任务配置',
    'automation_run': '自动化任务执行记录',
    'calendar': '用户日历',
    'calendar_event': '日历事件',
    'calendar_event_attendee': '日历事件参与者',
    'channel': '协作频道',
    'channel_file': '频道关联文件',
    'channel_member': '频道成员',
    'channel_webhook': '频道 Webhook 配置',
    'chat': '聊天会话',
    'chat_file': '聊天会话关联文件',
    'chat_message': '聊天消息',
    'config': '系统配置项',
    'document': '知识库文档',
    'feedback': '用户反馈',
    'file': '上传文件元数据',
    'folder': '聊天文件夹',
    'function': '函数工具定义',
    'group': '用户组',
    'group_member': '用户组成员关系',
    'knowledge': '知识库',
    'knowledge_directory': '知识库目录',
    'knowledge_file': '知识库文件关系',
    'memory': '用户记忆',
    'message': '频道消息',
    'message_reaction': '消息表情反应',
    'model': '模型配置',
    'note': '用户笔记',
    'oauth_session': 'OAuth 会话',
    'pinned_note': '置顶笔记关系',
    'prompt': '提示词模板',
    'prompt_history': '提示词修改历史',
    'shared_chat': '共享聊天会话',
    'skill': '技能定义',
    'tag': '聊天标签',
    'tool': '工具定义',
    'user': '用户账户',
}


COLUMN_COMMENTS = {
    'id': '记录唯一标识',
    'user_id': '所属用户标识',
    'group_id': '所属用户组标识',
    'channel_id': '所属频道标识',
    'chat_id': '所属聊天会话标识',
    'message_id': '所属消息标识',
    'event_id': '所属日历事件标识',
    'calendar_id': '所属日历标识',
    'file_id': '关联文件标识',
    'folder_id': '所属文件夹标识',
    'knowledge_id': '所属知识库标识',
    'directory_id': '所属目录标识',
    'model_id': '关联模型标识',
    'automation_id': '所属自动化任务标识',
    'name': '名称',
    'title': '标题',
    'description': '描述',
    'content': '正文内容',
    'chat': '聊天会话 JSON 数据',
    'data': '业务扩展 JSON 数据',
    'meta': '元数据 JSON',
    'settings': '用户设置 JSON',
    'info': '用户附加信息 JSON',
    'params': '模型参数 JSON',
    'variables': '聊天变量 JSON',
    'tasks': '聊天任务 JSON',
    'specs': '工具规格 JSON',
    'valves': '工具参数 JSON',
    'sources': '引用来源 JSON',
    'files': '关联文件 JSON',
    'embeds': '嵌入信息 JSON',
    'usage': '模型用量统计 JSON',
    'status_history': '状态变更历史 JSON',
    'error': '错误信息',
    'email': '电子邮箱',
    'password': '密码哈希',
    'active': '是否启用',
    'is_active': '是否启用',
    'is_global': '是否全局可用',
    'is_private': '是否私有',
    'is_default': '是否默认项',
    'is_cancelled': '是否已取消',
    'archived': '是否已归档',
    'pinned': '是否已置顶',
    'role': '角色',
    'type': '类型',
    'status': '状态',
    'permission': '权限',
    'created_at': '创建时间（Unix 时间戳）',
    'updated_at': '更新时间（Unix 时间戳）',
    'deleted_at': '删除时间（Unix 时间戳）',
    'archived_at': '归档时间（Unix 时间戳）',
    'last_active_at': '最后活跃时间（Unix 时间戳）',
    'timestamp': '时间戳',
    'start_at': '开始时间（Unix 时间戳）',
    'end_at': '结束时间（Unix 时间戳）',
    'last_run_at': '上次执行时间（Unix 时间戳）',
    'next_run_at': '下次执行时间（Unix 时间戳）',
    'api_key': 'API 密钥',
    'profile_image_url': '头像地址',
    'filename': '文件名',
    'path': '文件路径',
    'color': '颜色值',
    'location': '地点',
    'rrule': '重复规则',
    'command': '提示词命令',
    'tag_name': '标签名称',
    'base_model_id': '基础模型标识',
    'principal_id': '授权主体标识',
    'principal_type': '授权主体类型',
    'resource_id': '授权资源标识',
    'resource_type': '授权资源类型',
    'expires_at': '过期时间（Unix 时间戳）',
    'key': '配置键或访问密钥',
    'last_used_at': '最后使用时间（Unix 时间戳）',
    'all_day': '是否全天事件',
    'updated_by': '最后修改者标识',
    'archived_by': '归档操作者标识',
    'deleted_by': '删除操作者标识',
    'invited_at': '邀请时间（Unix 时间戳）',
    'invited_by': '邀请者标识',
    'is_channel_muted': '是否已静音频道',
    'is_channel_pinned': '是否已置顶频道',
    'joined_at': '加入时间（Unix 时间戳）',
    'left_at': '离开时间（Unix 时间戳）',
    'last_read_at': '最后阅读时间（Unix 时间戳）',
    'share_id': '共享链接标识',
    'summary': '摘要',
    'timer_at': '定时执行时间（Unix 时间戳）',
    'context_summary': '上下文摘要',
    'done': '是否处理完成',
    'output': '处理输出 JSON',
    'parent_id': '父记录标识',
    'value': '配置值',
    'snapshot': '版本快照 JSON',
    'version': '版本号',
    'hash': '文件内容哈希',
    'is_expanded': '是否展开',
    'items': '文件夹项目 JSON',
    'permissions': '组权限 JSON',
    'is_pinned': '是否已置顶',
    'pinned_at': '置顶时间（Unix 时间戳）',
    'pinned_by': '置顶操作者标识',
    'reply_to_id': '回复目标消息标识',
    'provider': 'OAuth 服务提供商',
    'token': '访问令牌',
    'note_id': '关联笔记标识',
    'tags': '提示词标签 JSON',
    'version_id': '版本标识',
    'commit_message': '版本提交说明',
    'prompt_id': '关联提示词标识',
}


def apply_metadata_comments(metadata: MetaData) -> None:
    """Apply comments to tables and columns already registered in metadata."""
    for table in metadata.tables.values():
        if table.name in TABLE_COMMENTS:
            table.comment = TABLE_COMMENTS[table.name]
        for column in table.columns:
            if column.name in COLUMN_COMMENTS:
                column.comment = COLUMN_COMMENTS[column.name]
