apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
  namespace: artha-ai
type: Opaque
stringData:
  WEBUI_SECRET_KEY: "replace-with-random-secret"
  OAUTH_CLIENT_SECRET: "replace-with-keycloak-client-secret"
  DATABASE_URL: "postgresql://open_webui:replace-password@artha-prod-aps1-aurora.cluster-c3s00kkeqp20.ap-south-1.rds.amazonaws.com:5432/replace-existing-database-name"
  DATABASE_SCHEMA: "open_webui"
