"""
ComfyUI Workflow Templates Package
export workflows
"""

from .text2img import (
    WORKFLOW as TEXT2IMG_WORKFLOW,
    MAIN_NODE_ID as TEXT2IMG_MAIN_NODE_ID,
    PARAM_MAPPING as TEXT2IMG_PARAM_MAPPING,
    DEFAULT_PARAMS as TEXT2IMG_DEFAULT_PARAMS,
)

from .img2img import (
    WORKFLOW as IMG2IMG_WORKFLOW,
    MAIN_NODE_ID as IMG2IMG_MAIN_NODE_ID,
    IMAGE_LOADER_NODES as IMG2IMG_IMAGE_LOADER_NODES,
    PARAM_MAPPING as IMG2IMG_PARAM_MAPPING,
    DEFAULT_PARAMS as IMG2IMG_DEFAULT_PARAMS,
)

from .fusion2imgs import (
    WORKFLOW as FUSION2IMGS_WORKFLOW,
    MAIN_NODE_ID as FUSION2IMGS_MAIN_NODE_ID,
    IMAGE_LOADER_NODES as FUSION2IMGS_IMAGE_LOADER_NODES,
    PARAM_MAPPING as FUSION2IMGS_PARAM_MAPPING,
    DEFAULT_PARAMS as FUSION2IMGS_DEFAULT_PARAMS,
)

# export
__all__ = [
    # text2img
    "TEXT2IMG_WORKFLOW",
    "TEXT2IMG_MAIN_NODE_ID",
    "TEXT2IMG_PARAM_MAPPING",
    "TEXT2IMG_DEFAULT_PARAMS",
    
    # img2img
    "IMG2IMG_WORKFLOW",
    "IMG2IMG_MAIN_NODE_ID",
    "IMG2IMG_IMAGE_LOADER_NODES",
    "IMG2IMG_PARAM_MAPPING",
    "IMG2IMG_DEFAULT_PARAMS",
    
    # fusion
    "FUSION2IMGS_WORKFLOW",
    "FUSION2IMGS_MAIN_NODE_ID",
    "FUSION2IMGS_IMAGE_LOADER_NODES",
    "FUSION2IMGS_PARAM_MAPPING",
    "FUSION2IMGS_DEFAULT_PARAMS",
]