import './global.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

// Conceptual ThemeProvider, assuming ShadCN/Next-themes
const ThemeProvider = ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>; // Replace with actual ThemeProvider implementation
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
