# Example Client Configuration
# This is a filled-out example for reference

client:
  id: "techcorp"
  name: "TechCorp Industries"
  domain: "ai.techcorp.com"
  contact:
    name: "John Smith"
    email: "john.smith@techcorp.com"
    phone: "+1-555-123-4567"

branding:
  appName: "TechCorp AI Assistant"
  tagline:
    en: "Empowering Innovation with AI"
    pl: "Wspieranie innowacji z AI"
  logo:
    light: "assets/techcorp-logo.png"
    dark: "assets/techcorp-logo-dark.png"
  colors:
    primary: "#FF6B35"
    secondary: "#F7931E"

features:
  backgroundPatterns:
    enabled: true
    allowedTypes: ["dots"]
    defaultType: "dots"
    defaultOpacity: 0.03
  
  customThemes:
    enabled: true
    themes: ["professional", "warm"]
  
  fontSizeControl:
    enabled: true
    defaultSize: "normal"
  
  polishLanguage:
    enabled: false
  
  auth:
    singleUser: false
    providers:
      - "oidc"  # Using corporate SSO

deployment:
  environment: "production"
  
  server:
    provider: "hetzner"
    location: "fsn1"
    specs:
      cpu: 4
      ram: 16
      storage: 200
  
  docker:
    registry: "registry.techcorp.com"
    namespace: "mai"
    imageTag: "v1.0.0"
  
  database:
    type: "postgresql"
    backup:
      enabled: true
      schedule: "0 3 * * *"
      retention: 30
  
  ssl:
    provider: "letsencrypt"
    email: "devops@techcorp.com"
  
  monitoring:
    enabled: true
    provider: "datadog"
    alerting:
      email: "alerts@techcorp.com"
      pagerduty: "https://events.pagerduty.com/v2/enqueue"

security:
  allowedOrigins:
    - "https://ai.techcorp.com"
    - "https://internal.techcorp.com"
  
  rateLimit:
    enabled: true
    requests: 200
    window: 60
  
  contentPolicy:
    maxFileSize: 100
    allowedFileTypes:
      - "pdf"
      - "txt"
      - "docx"
      - "xlsx"
      - "pptx"
      - "csv"

integrations:
  ollama:
    url: "http://ollama.techcorp.internal:11434"
    models:
      - "llama3.2:latest"
      - "codellama:latest"
      - "mistral:latest"
  
  openai:
    enabled: true
    apiKey: "${OPENAI_API_KEY}"
    models:
      - "gpt-4"
      - "gpt-3.5-turbo"
  
  anthropic:
    enabled: false
    apiKey: "${ANTHROPIC_API_KEY}"

env:
  ENABLE_METRICS: "true"
  LOG_LEVEL: "info"
  CORS_ALLOWED_ORIGINS: "https://techcorp.com,https://app.techcorp.com"