# Client Configuration Template
# Copy this file to deployments/clients/[client-name]/config/client.yaml

client:
  id: "client-id"              # Unique identifier (lowercase, no spaces)
  name: "Client Name"          # Display name
  domain: "ai.client.com"      # Production domain
  contact:
    name: "Client Contact"
    email: "contact@client.com"
    phone: "+1-234-567-8900"

branding:
  appName: "Client AI Portal"  # Override mAI name
  tagline:
    en: "Powered by mAI Technology"
    pl: "Napędzane technologią mAI"
  logo:
    light: "assets/client-logo-light.png"
    dark: "assets/client-logo-dark.png"
  colors:
    primary: "#0066CC"
    secondary: "#0052A3"

features:
  # Feature toggles
  backgroundPatterns:
    enabled: true
    allowedTypes: ["dots", "grid"]  # Limit available patterns
    defaultType: "dots"
    defaultOpacity: 0.05
  
  customThemes:
    enabled: true
    themes: ["professional", "minimalist"]  # Only these themes available
  
  fontSizeControl:
    enabled: true
    defaultSize: "normal"
  
  polishLanguage:
    enabled: false  # Disable if not needed
  
  auth:
    singleUser: false  # Multi-user mode
    providers:
      - "local"
      - "oidc"

deployment:
  environment: "production"
  
  server:
    provider: "hetzner"
    location: "fsn1"  # Falkenstein, Germany
    specs:
      cpu: 4
      ram: 8
      storage: 100
  
  docker:
    registry: "registry.hetzner.com"
    namespace: "mai-clients"
    imageTag: "latest"
  
  database:
    type: "postgresql"  # or "mysql", "sqlite"
    backup:
      enabled: true
      schedule: "0 2 * * *"  # Daily at 2 AM
      retention: 30  # days
  
  ssl:
    provider: "letsencrypt"
    email: "ssl@client.com"
  
  monitoring:
    enabled: true
    provider: "prometheus"
    alerting:
      email: "alerts@client.com"
      slack: "https://hooks.slack.com/services/..."

security:
  allowedOrigins:
    - "https://ai.client.com"
    - "https://www.client.com"
  
  rateLimit:
    enabled: true
    requests: 100
    window: 60  # seconds
  
  contentPolicy:
    maxFileSize: 50  # MB
    allowedFileTypes:
      - "pdf"
      - "txt"
      - "docx"
      - "xlsx"

integrations:
  ollama:
    url: "http://ollama:11434"
    models:
      - "llama3.2:latest"
      - "mistral:latest"
  
  openai:
    enabled: false
    apiKey: "${OPENAI_API_KEY}"  # From environment
  
  anthropic:
    enabled: false
    apiKey: "${ANTHROPIC_API_KEY}"

# Custom environment variables
env:
  CUSTOM_VAR_1: "value1"
  CUSTOM_VAR_2: "value2"