<script lang="ts">
	import { toast } from 'svelte-sonner';

	import { createEventDispatcher, onMount, getContext } from 'svelte';
	import { config, models, tags as _tags } from '$lib/stores';
	import Tags from '$lib/components/common/Tags.svelte';
	import XMark from '$lib/components/icons/XMark.svelte';

	const i18n = getContext('i18n');

	const dispatch = createEventDispatcher();

	export let message;
	export let show = false;

	let LIKE_REASONS = [
		'covered_all_details',
		'covered_extra_details',
		'showed_image_and_text_properly',
		'other'
	];
	let DISLIKE_REASONS = [
		'giving_stale_info',
		'wrong_info',
		'stt_not_working',
		'tts_not_working',
		'other'
	];

	let tags = [];

	let reasons = [];
	let selectedReason = null;
	let comment = '';

	let detailedRating = null;
	let selectedModel = null;

	const getReasonLabel = (reason: string) => {
		switch (reason) {
			case 'covered_all_details':
				return 'Covered all details';
			case 'covered_extra_details':
				return 'Covered extra details';
			case 'showed_image_and_text_properly':
				return 'Showed image and text properly';
			case 'giving_stale_info':
				return 'Giving stale info';
			case 'wrong_info':
				return 'Wrong info';
			case 'stt_not_working':
				return 'STT not working';
			case 'tts_not_working':
				return 'TTS not working';
			case 'other':
				return '';
			default:
				return reason;
		}
	};

	const handleReasonClick = (reason: string) => {
		selectedReason = reason;
		const label = getReasonLabel(reason);
		if (label) {
			if (!comment.trim()) {
				comment = label;
			} else if (!comment.includes(label)) {
				comment = `${comment.trim()}, ${label}`;
			}
		}
	};

	$: if (message?.annotation?.rating === 1) {
		reasons = LIKE_REASONS;
	} else if (message?.annotation?.rating === -1) {
		reasons = DISLIKE_REASONS;
	}

	$: if (message) {
		init();
	}

	const init = () => {
		if (!selectedReason) {
			selectedReason = message?.annotation?.reason ?? '';
		}

		if (!comment) {
			comment = message?.annotation?.comment ?? '';
		}

		tags = (message?.annotation?.tags ?? []).map((tag) => ({
			name: tag
		}));

		if (!detailedRating) {
			detailedRating = message?.annotation?.details?.rating ?? null;
		}
	};

	onMount(() => {
		if (message?.arena) {
			selectedModel = $models.find((m) => m.id === message.selectedModelId);
			toast.success(
				$i18n.t('This response was generated by "{{model}}"', {
					model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
				})
			);
		}
	});

	const saveHandler = () => {
		console.log('saveHandler');
		// if (!selectedReason) {
		// 	toast.error($i18n.t('Please select a reason'));
		// 	return;
		// }

		dispatch('save', {
			reason: selectedReason,
			comment: comment,
			tags: tags.map((tag) => tag.name),
			details: {
				rating: detailedRating
			}
		});

		toast.success($i18n.t('Thanks for your feedback!'));
		show = false;
	};
</script>

{#if message?.arena}
	<div class="text-xs font-normal pt-1.5 -mb-0.5">
		{$i18n.t('This response was generated by "{{model}}"', {
			model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
		})}
	</div>
{/if}

<div
	class=" my-2.5 rounded-xl px-4 py-3 border border-gray-100/30 dark:border-gray-850/30"
	id="message-feedback-{message.id}"
>
	<div class="flex justify-between items-center">
		<div class="text-sm font-normal">{$i18n.t('How would you rate this response?')}</div>

		<!-- <div class=" text-sm">{$i18n.t('Tell us more:')}</div> -->

		<button
			aria-label={$i18n.t('Close feedback')}
			on:click={() => {
				show = false;
			}}
		>
			<XMark className={'size-4'} />
		</button>
	</div>

	<div class="w-full overflow-x-auto">
		<div class="relative mx-auto min-w-[19rem] max-w-80">
			<div class="mt-1.5 grid grid-cols-10 gap-1 pb-2">
				<!-- 1-10 scale -->
				{#each Array.from({ length: 10 }).map((_, i) => i + 1) as rating}
					<button
						aria-label={$i18n.t('Rate {{rating}} out of 10', { rating })}
						class="aspect-square w-full text-sm border border-gray-100/30 dark:border-gray-850/30 hover:bg-gray-50 dark:hover:bg-gray-850 {detailedRating ===
						rating
							? 'bg-gray-100 dark:bg-gray-800'
							: ''} transition rounded-full disabled:cursor-not-allowed disabled:text-gray-500 disabled:bg-white dark:disabled:bg-gray-900"
						on:click={() => {
							detailedRating = rating;
						}}
						disabled={message?.annotation?.rating === -1 ? rating > 5 : rating < 6}
					>
						{rating}
					</button>
				{/each}
			</div>

			<div class="sticky top-0 bottom-0 left-0 right-0 flex justify-between text-xs">
				<div>
					1 - {$i18n.t('Awful')}
				</div>

				<div>
					10 - {$i18n.t('Amazing')}
				</div>
			</div>
		</div>
	</div>

	<div>
		{#if reasons.length > 0}
			<div class="text-sm mt-1.5 font-normal">{$i18n.t('Why?')}</div>

			<div class="flex flex-wrap gap-1.5 text-sm mt-1.5">
				{#each reasons as reason}
					<button
						class="px-3 py-0.5 border border-gray-100/30 dark:border-gray-850/30 hover:bg-gray-50 dark:hover:bg-gray-850 {selectedReason ===
						reason
							? 'bg-gray-100 dark:bg-gray-800'
							: ''} transition rounded-xl"
						on:click={() => {
							handleReasonClick(reason);
						}}
					>
						{#if reason === 'covered_all_details'}
							Covered all details
						{:else if reason === 'covered_extra_details'}
							Covered extra details
						{:else if reason === 'showed_image_and_text_properly'}
							Showed image and text properly
						{:else if reason === 'giving_stale_info'}
							Giving stale info
						{:else if reason === 'wrong_info'}
							Wrong info
						{:else if reason === 'stt_not_working'}
							STT not working
						{:else if reason === 'tts_not_working'}
							TTS not working
						{:else if reason === 'other'}
							{$i18n.t('Other')}
						{:else}
							{reason}
						{/if}
					</button>
				{/each}
			</div>
		{/if}
	</div>

	<div class="mt-2">
		<textarea
			bind:value={comment}
			class="w-full text-sm px-1 py-2 bg-transparent outline-hidden resize-none rounded-xl"
			placeholder={$i18n.t('Feel free to add specific details')}
			aria-label={$i18n.t('Additional feedback comments')}
			rows="3"
		/>
	</div>

	<div class="mt-2 gap-1.5 flex justify-between">
		<div class="flex items-end group">
			<Tags
				{tags}
				suggestionTags={$_tags ?? []}
				on:delete={(e) => {
					tags = tags.filter(
						(tag) =>
							tag.name.replaceAll(' ', '_').toLowerCase() !==
							e.detail.replaceAll(' ', '_').toLowerCase()
					);
				}}
				on:add={(e) => {
					tags = [...tags, { name: e.detail }];
				}}
			/>
		</div>

		<button
			class="px-3.5 py-1.5 text-sm font-normal bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-full"
			on:click={() => {
				saveHandler();
			}}
		>
			{$i18n.t('Save')}
		</button>
	</div>
</div>
