<script lang="ts">
	import { toast } from 'svelte-sonner';

	import { createEventDispatcher, onMount, getContext } from 'svelte';
	import { config, models } from '$lib/stores';
	import Tags from '$lib/components/common/Tags.svelte';
	import MaterialIcon from '$lib/components/common/MaterialIcon.svelte';
	import type { i18n as i18nType } from 'i18next';
	import type { Writable } from 'svelte/store';

	const i18n = getContext<Writable<i18nType>>('i18n');

	const dispatch = createEventDispatcher();

	export let message;
	export let show = false;

	let LIKE_REASONS = [
		{
			key: 'accurate_correct',
			header: 'Accurate & correct',
			sub: 'Facts match trusted sources'
		},
		{
			key: 'clear_easy',
			header: 'Clear & easy to follow',
			sub: 'Writing is straightforward, no complicated jargon'
		},
		{
			key: 'complete_detailed',
			header: 'Complete & detailed',
			sub: 'Covers the topic thoroughly'
		},
		{
			key: 'relevant_need',
			header: 'Relevant to my need',
			sub: 'Directly answers my question'
		},
		{
			key: 'well_structured',
			header: 'Well structured & formatted',
			sub: 'Logical flow, tidy layout'
		},
		{
			key: 'other',
			header: 'Other',
			sub: ''
		}
	];
	let DISLIKE_REASONS = [
		{
			key: 'factually_incorrect',
			header: 'Factually incorrect',
			sub: 'Contains the wrong or misleading info'
		},
		{
			key: 'unclear_confusing',
			header: 'Unclear or confusing',
			sub: 'Hard to read or understand'
		},
		{
			key: 'incomplete_missing',
			header: 'Incomplete/missing details',
			sub: 'Too brief and important points left out'
		},
		{
			key: 'off_topic',
			header: 'Off-topic and irrelevant',
			sub: "Doesnt' address my question"
		},
		{
			key: 'too_technical',
			header: 'Too technical or jargon-heavy',
			sub: "Uses terms the average reader won't know"
		},
		{
			key: 'poor_structure',
			header: 'Poor structure or formatting',
			sub: 'Disorganized or visually messy'
		},
		{
			key: 'other',
			header: 'Other',
			sub: ''
		}
	];

	let tags: { name: string }[] = [];
	let reasons: { key: string; header: string; sub: string }[] = [];
	let selectedReason: string | null = null;
	let comment = '';

	let detailedRating: any = null;
	let selectedModel: any = null;

	$: if (message?.annotation?.rating === 1) {
		reasons = LIKE_REASONS;
	} else if (message?.annotation?.rating === -1) {
		reasons = DISLIKE_REASONS;
	}

	$: if (message) {
		init();
	}

	const init = () => {
		if (!selectedReason) {
			selectedReason = message?.annotation?.reason ?? '';
		}

		if (!comment) {
			comment = message?.annotation?.comment ?? '';
		}

		tags = (message?.annotation?.tags ?? []).map((tag: string) => ({
			name: tag
		}));

		if (!detailedRating) {
			detailedRating = message?.annotation?.details?.rating ?? null;
		}
	};

	onMount(() => {
		if (message?.arena) {
			selectedModel = $models.find((m) => m.id === message.selectedModelId);
			toast.success(
				$i18n.t('This response was generated by "{{model}}"', {
					model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
				})
			);
		}
	});

	const saveHandler = () => {
		console.log('saveHandler');
		// if (!selectedReason) {
		// 	toast.error($i18n.t('Please select a reason'));
		// 	return;
		// }

		dispatch('save', {
			reason: selectedReason,
			comment: comment,
			tags: tags.map((tag) => tag.name),
			details: {
				rating: detailedRating
			}
		});

		toast.success($i18n.t('Thanks for your feedback!'));
		show = false;
	};
</script>

{#if message?.arena}
	<div class="text-xs font-medium pt-1.5 -mb-0.5">
		{$i18n.t('This response was generated by "{{model}}"', {
			model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
		})}
	</div>
{/if}

<div
	class=" my-2.5 rounded-xl px-4 py-3 border border-gray-100 dark:border-gray-850 bg-white dark:bg-gray-900"
	id="message-feedback-{message.id}"
>
	<div class="flex justify-between items-center">
		<div class="text-sm font-medium">
			<div class="flex items-center gap-1">
				{#if message?.annotation?.rating === 1}
					<div>
						<MaterialIcon name="thumb_up" size="1.4rem" color="#18795F" />
						<div class="mt-2 text-[#2FA27F] font-inter text-[24px] font-semibold leading-[30px]">
							{$i18n.t('Glad that helped!')}
						</div>
						<div class="mt-1 text-[#2FA27F] font-inter text-[16px] font-medium leading-[24px]">
							{$i18n.t('Thank you for your feedback. Please let me know what did you find helpful?')}
						</div>
					</div>
				{:else}
					<div>
						<MaterialIcon name="thumb_down" size="1.4rem" color="#E6620D" />
						<div class="mt-2 text-[#E6620D] font-inter text-[24px] font-semibold leading-[30px]">
							{$i18n.t('Sorry about that')}
						</div>
						<div class="mt-1 text-[#E6620D] font-inter text-[16px] font-medium leading-[24px]">
							{$i18n.t('Help us improve, what went wrong with the response?')}
						</div>
					</div>
				{/if}
			</div>
		</div>
		<!-- <div class=" text-sm">{$i18n.t('Tell us more:')}</div> -->

		<button
			on:click={() => {
				show = false;
			}}
		>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				fill="none"
				viewBox="0 0 24 24"
				stroke-width="1.5"
				stroke="currentColor"
				class="size-4"
			>
				<path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
			</svg>
		</button>
	</div>

	<div>
		{#if reasons.length > 0}
			<div class="flex flex-wrap gap-1.5 text-sm mt-1.5 py-2">
				{#each reasons as reason}
					<button
						class="px-3 py-0.5 border border-gray-100 dark:border-gray-850 hover:bg-gray-50 dark:hover:bg-gray-850 {selectedReason ===
						reason.key
							? 'bg-gray-100 dark:bg-gray-800'
							: ''} transition rounded-3xl flex flex-col items-center min-w-[200px]"
						on:click={() => {
							selectedReason = reason.key;
						}}
					>
						<span class="font-semibold p-2">{reason.header}</span>
					</button>
				{/each}
			</div>
		{/if}
	</div>

	{#if selectedReason === 'other'}
		<div class="mt-2">
			<textarea
				bind:value={comment}
				class="w-full text-sm px-1 py-2 bg-transparent outline-hidden resize-none rounded-xl border border-gray-100 dark:border-gray-850"
				placeholder={$i18n.t('Feel free to add specific details')}
				rows="3"
			/>
		</div>
	{/if}

	<div class="mt-2 gap-1.5 flex justify-end">
		<button
			class="px-3.5 py-1.5 text-sm font-medium bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-full"
			on:click={() => {
				saveHandler();
			}}
		>
			{$i18n.t('Save')}
		</button>
	</div>
</div>
