import { app, BrowserWindow } from 'electron';
import { logInfo, logError } from './logger';
import { getAppInstallDir, isDev } from './envUtils';
import { handleSquirrelEvent } from './squirrelEvents';
import { rauxProcessManager } from './rauxProcessManager';
import { setTimeout } from 'timers';
import { writeFileSync } from 'fs';
import { mkdirSync } from 'fs';
import { join } from 'path';
import { python } from './pythonExec';
import { raux } from './rauxSetup';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const RAUX_URL = 'http://localhost:8080';

logInfo(`Main process started\nArgs: ${process.argv.join(' ')}\n`);

if (handleSquirrelEvent()) {
  // Squirrel event handled, exit early
  process.exit(0);
}

logInfo(`Current Environment: ${isDev ? 'Development' : 'Production'}`);
logInfo(`Install dir: ${getAppInstallDir()}`);
logInfo(`RAUX Version: ${process.env.RAUX_VERSION || 'latest'}`);

const createWindow = async (): Promise<void> => {
  try {
    logInfo('Calling createWindow');

    await python.install();
    await raux.install();

    // Create the browser window.
    const mainWindow = new BrowserWindow({
      height: 600,
      width: 800,
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      },
    });

    // Always load the Webpack entry point, regardless of dev or prod
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Start RAUX backend
    rauxProcessManager.startRaux();

    // Poll for backend readiness
    const pollBackend = () => {
      fetch(RAUX_URL)
        .then(() => {
          mainWindow.loadURL(RAUX_URL);
        })
        .catch(() => {
          if (rauxProcessManager.getStatus() === 'crashed') {
            mainWindow.loadURL('data:text/html,<h1>RAUX failed to start</h1>');
          } else {
            setTimeout(pollBackend, 1000);
          }
        });
    };
    pollBackend();

    // Open the DevTools.
    // mainWindow.webContents.openDevTools(); // Uncomment for debugging
  } catch (err) {
    logError('Error in createWindow: ' + (err && err.toString ? err.toString() : String(err)));
    throw err;
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
