"""Add MCP server table

Revision ID: 118d4ef0454d
Revises: c76c3d700261
Create Date: 2024-12-15 10:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "118d4ef0454d"
down_revision: Union[str, None] = "c76c3d700261"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_server",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("server_type", sa.String(), nullable=True, default="user_created"),
        sa.Column("command", sa.Text(), nullable=True),
        sa.Column("args", sa.JSON(), nullable=True, default="[]"),
        sa.Column("env", sa.JSON(), nullable=True, default="{}"),
        sa.Column("transport", sa.String(), nullable=True, default="stdio"),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True, default=True),
        sa.Column("is_deletable", sa.Boolean(), nullable=True, default=True),
        sa.Column("capabilities", sa.JSON(), nullable=True, default="{}"),
        sa.Column("tools", sa.JSON(), nullable=True, default="[]"),
        sa.Column("access_control", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mcp_server")
    # ### end Alembic commands ###
