"""Add revoked_at to chat table

Revision ID: 3a3b5c6d7e8f
Revises: 79fba6b72c04
Create Date: 2025-08-12 12:59:22.992221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3b5c6d7e8f'
down_revision: Union[str, None] = '79fba6b72c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revoked_at', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('revoked_at')

    # ### end Alembic commands ###
