"""a description

Revision ID: 5189885cf572
Revises: 82af2ebd8481
Create Date: 2025-03-04 19:52:33.701236

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

import open_webui.internal.db

# revision identifiers, used by Alembic.
revision: str = "5189885cf572"
down_revision: Union[str, None] = "82af2ebd8481"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model", sa.Column("price", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model", "price")
    # ### end Alembic commands ###
