"""Added grants table

Revision ID: 7e9b9c38bbdb
Revises: 3781e22d8b01
Create Date: 2025-04-08 15:28:27.730687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e9b9c38bbdb'
down_revision: Union[str, None] = '3781e22d8b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grants_feedback',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('chat_id', sa.Text(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('feedback_str', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

def downgrate() -> None:
    op.drop_table("grants_feedback")
