"""add share qr code options to chat

Revision ID: b45222af841c
Revises: 79fba6b72c04
Create Date: 2025-08-18 07:02:33.956380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45222af841c'
down_revision: Union[str, None] = '79fba6b72c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('share_show_qr_code', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('chat', sa.Column('share_use_gradient', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'share_use_gradient')
    op.drop_column('chat', 'share_show_qr_code')
    # ### end Alembic commands ###
