"""modify_agents_table_for_generic_model_id

Revision ID: 020
Revises: 019
Create Date: 2024-03-15 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020'
down_revision: Union[str, None] = '019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.alter_column('llm_model', new_column_name='model_id', existing_type=sa.String(), nullable=False)
        batch_op.create_foreign_key('fk_agent_model_id_model', 'model', ['model_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_model_id_model', type_='foreignkey')
        batch_op.alter_column('model_id', new_column_name='llm_model', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###
