"""Validation utilities for user-supplied input."""

import re
from urllib.parse import urlparse

# Validates the MIME type and structure of base64 data URIs, not payload
# integrity — corrupt base64 simply produces a broken image, same as a 404 URL.
# SVG is intentionally excluded: it can carry embedded scripts.
_SAFE_DATA_URI_RE = re.compile(
    r'^data:image/(png|jpeg|gif|webp);base64,', re.IGNORECASE
)

# Relative path prefixes that are safe to accept as profile image URLs.
# These are the only patterns OWUI itself generates; arbitrary relative
# paths are rejected to prevent authenticated GET triggers against
# internal endpoints when other users view a profile.
_SAFE_RELATIVE_PATH_PREFIXES = (
    '/api/v1/users/',  # OWUI-generated profile image routes
    '/static/',        # Static assets served by the frontend
)

# Exact relative paths accepted (default avatars).
_SAFE_RELATIVE_PATHS = frozenset({
    '/user.png',
    '/favicon.png',
})


def validate_profile_image_url(url: str) -> str:
    """
    Pydantic-compatible validator for profile image URLs.

    Allowed formats:
    - Empty string (falls back to default avatar)
    - Known-safe relative paths (default avatars, static assets,
      and OWUI profile image API routes)
    - ``http://`` and ``https://`` URLs with a valid host
    - ``data:image/{png,jpeg,gif,webp};base64,...`` URIs

    All other schemes (javascript:, file:, ftp:, etc.) are rejected.
    SVG data URIs are rejected because SVG can contain embedded scripts.
    Arbitrary relative paths are rejected to prevent authenticated GET
    requests against internal endpoints.
    """
    if not url:
        return url

    # Known-safe relative paths generated by OWUI itself.
    if url in _SAFE_RELATIVE_PATHS:
        return url
    if any(url.startswith(prefix) for prefix in _SAFE_RELATIVE_PATH_PREFIXES):
        return url

    # urlparse normalises the scheme to lowercase, giving us
    # case-insensitive scheme matching for free.
    parsed = urlparse(url)

    # External images served over HTTP(S), e.g. OAuth provider avatars.
    # Require a non-empty hostname (not just netloc, which can be ":80"
    # for a URL like http://:80/path with no actual host).
    if parsed.scheme in ('http', 'https'):
        if not parsed.hostname:
            raise ValueError(
                'Invalid profile image URL: HTTP(S) URLs must include a host.'
            )
        return url

    # Base64-encoded raster images uploaded via the frontend.
    # The regex enforces format boundaries (;base64,) and is
    # case-insensitive per the data URI / MIME type specs.
    if _SAFE_DATA_URI_RE.match(url):
        return url

    raise ValueError(
        'Invalid profile image URL: must be a known internal path, '
        'an HTTP(S) URL with a host, or a data:image URI (png/jpeg/gif/webp).'
    )


