
var ortWasmThreaded = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

function e(){l.buffer!=q.buffer&&t();return q}function w(){l.buffer!=q.buffer&&t();return aa}function ca(){l.buffer!=q.buffer&&t();return da}function ea(){l.buffer!=q.buffer&&t();return fa}function z(){l.buffer!=q.buffer&&t();return ha}function A(){l.buffer!=q.buffer&&t();return ia}function ja(){l.buffer!=q.buffer&&t();return ka}function la(){l.buffer!=q.buffer&&t();return ma}
var B=Object.assign({},moduleArg),na,oa,pa=new Promise((a,b)=>{na=a;oa=b}),qa="object"==typeof window,C="function"==typeof importScripts,D="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,E=C&&"em-pthread"==self.name;if(D){const {createRequire:a}=await import("module");var require=a(import.meta.url),ra=require("worker_threads");global.Worker=ra.Worker;E=(C=!ra.qc)&&"em-pthread"==ra.workerData}"use strict";
B.mountExternalData=(a,b)=>{a.startsWith("./")&&(a=a.substring(2));(B.Fb||(B.Fb=new Map)).set(a,b)};B.unmountExternalData=()=>{delete B.Fb};var SharedArrayBuffer=globalThis.SharedArrayBuffer??(new WebAssembly.Memory({initial:0,maximum:0,shared:!0})).buffer.constructor;"use strict";
let ta=()=>{const a=(c,d,f)=>(...g)=>{const k=F,m=d?.();g=c(...g);const p=d?.();m!==p&&(c=p,f(m),d=f=null);return F!=k?sa():g},b=c=>async(...d)=>{try{if(B.Gb)throw Error("Session already started");const f=B.Gb={hc:d[0],errors:[]},g=await c(...d);if(B.Gb!==f)throw Error("Session mismatch");B.Hb?.flush();const k=f.errors;if(0<k.length){let m=await Promise.all(k);m=m.filter(p=>p);if(0<m.length)throw Error(m.join("\n"));}return g}finally{B.Gb=null}};B._OrtCreateSession=a(B._OrtCreateSession,()=>B._OrtCreateSession,
c=>B._OrtCreateSession=c);B._OrtRun=b(a(B._OrtRun,()=>B._OrtRun,c=>B._OrtRun=c));B._OrtRunWithBinding=b(a(B._OrtRunWithBinding,()=>B._OrtRunWithBinding,c=>B._OrtRunWithBinding=c));B._OrtBindInput=a(B._OrtBindInput,()=>B._OrtBindInput,c=>B._OrtBindInput=c);ta=void 0};
B.jsepInit=(a,b)=>{ta?.();if("webgpu"===a){[B.Hb,B.Vb,B.Zb,B.Ob,B.Yb,B.kb,B.$b,B.cc,B.Wb,B.Xb,B.ac]=b;const c=B.Hb;B.jsepRegisterBuffer=(d,f,g,k)=>c.registerBuffer(d,f,g,k);B.jsepGetBuffer=d=>c.getBuffer(d);B.jsepCreateDownloader=(d,f,g)=>c.createDownloader(d,f,g);B.jsepOnCreateSession=d=>{c.onCreateSession(d)};B.jsepOnReleaseSession=d=>{c.onReleaseSession(d)};B.jsepOnRunStart=d=>c.onRunStart(d);B.dc=(d,f)=>{c.upload(d,f)}}else if("webnn"===a){[B.Hb,B.bc,B.Pb,B.jsepEnsureTensor,B.ec,B.jsepDownloadTensor]=
b;B.jsepReleaseTensorId=B.Pb;const c=B.Hb;B.jsepOnRunStart=d=>c.onRunStart(d);B.jsepRegisterMLContext=(d,f)=>{c.registerMLContext(d,f)};B.jsepOnReleaseSession=d=>{c.onReleaseSession(d)};B.jsepCreateMLTensorDownloader=(d,f)=>c.createMLTensorDownloader(d,f);B.jsepRegisterMLTensor=(d,f,g)=>c.registerMLTensor(d,f,g);B.jsepCreateMLContext=d=>c.createMLContext(d);B.jsepRegisterMLConstant=(d,f,g,k,m)=>c.registerMLConstant(d,f,g,k,m,B.Fb)}};
var ua=Object.assign({},B),va="./this.program",wa=(a,b)=>{throw b;},G="",xa,ya,za;
if(D){var fs=require("fs"),Aa=require("path");G=require("url").fileURLToPath(new URL("./",import.meta.url));xa=(a,b)=>{a=Ba(a)?new URL(a):Aa.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};za=a=>{a=xa(a,!0);a.buffer||(a=new Uint8Array(a));return a};ya=(a,b,c,d=!0)=>{a=Ba(a)?new URL(a):Aa.normalize(a);fs.readFile(a,d?void 0:"utf8",(f,g)=>{f?c(f):b(d?g.buffer:g)})};!B.thisProgram&&1<process.argv.length&&(va=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);wa=(a,b)=>{process.exitCode=
a;throw b;}}else if(qa||C)C?G=self.location.href:"undefined"!=typeof document&&document.currentScript&&(G=document.currentScript.src),_scriptName&&(G=_scriptName),G.startsWith("blob:")?G="":G=G.substr(0,G.replace(/[?#].*/,"").lastIndexOf("/")+1),D||(xa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},C&&(za=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ya=(a,b,c)=>{var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)});D&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var Ca=console.log.bind(console),Da=console.error.bind(console);D&&(Ca=(...a)=>fs.writeSync(1,a.join(" ")+"\n"),Da=(...a)=>fs.writeSync(2,a.join(" ")+"\n"));var Ea=Ca,H=Da;Object.assign(B,ua);ua=null;
if(E){var Fa;if(D){var Ga=ra.parentPort;Ga.on("message",b=>onmessage({data:b}));Object.assign(globalThis,{self:global,importScripts:()=>{},postMessage:b=>Ga.postMessage(b),performance:global.performance||{now:Date.now}})}var Ha=!1;H=function(...b){b=b.join(" ");D?fs.writeSync(2,b+"\n"):console.error(b)};self.alert=function(...b){postMessage({Nb:"alert",text:b.join(" "),rc:Ia()})};B.instantiateWasm=(b,c)=>new Promise(d=>{Fa=f=>{f=new WebAssembly.Instance(f,Ja());c(f);d()}});self.onunhandledrejection=
b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.cmd;if("load"===d){let f=[];self.onmessage=g=>f.push(g);self.startWorker=()=>{postMessage({cmd:"loaded"});for(let g of f)a(g);self.onmessage=a};for(const g of c.handlers)if(!B[g]||B[g].proxy)B[g]=(...k)=>{postMessage({Nb:"callHandler",pc:g,args:k})},"print"==g&&(Ea=B[g]),"printErr"==g&&(H=B[g]);l=c.wasmMemory;t();Fa(c.wasmModule)}else if("run"===d){Ka(c.pthread_ptr,0,0,1,0,0);La(c.pthread_ptr);Ma();Na();Ha||(Oa(),Ha=!0);try{Pa(c.start_routine,
c.arg)}catch(f){if("unwind"!=f)throw f;}}else"cancel"===d?Ia()&&Qa(-1):"setimmediate"!==c.target&&("checkMailbox"===d?Ha&&Ra():d&&(H(`worker: received unknown command ${d}`),H(c)))}catch(f){throw Sa(),f;}}self.onmessage=a}var Ta;B.wasmBinary&&(Ta=B.wasmBinary);var l,Ua,I=!1,Va,q,aa,da,fa,ha,ia,ka,J,Wa,ma;
function t(){var a=l.buffer;B.HEAP8=q=new Int8Array(a);B.HEAP16=da=new Int16Array(a);B.HEAPU8=aa=new Uint8Array(a);B.HEAPU16=fa=new Uint16Array(a);B.HEAP32=ha=new Int32Array(a);B.HEAPU32=ia=new Uint32Array(a);B.HEAPF32=ka=new Float32Array(a);B.HEAPF64=ma=new Float64Array(a);B.HEAP64=J=new BigInt64Array(a);B.HEAPU64=Wa=new BigUint64Array(a)}
if(!E){l=new WebAssembly.Memory({initial:256,maximum:65536,shared:!0});if(!(l.buffer instanceof SharedArrayBuffer))throw H("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),D&&H("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),Error("bad memory");t()}
var Xa=[],Ya=[],Za=[],$a=0,ab=null,bb=null;function cb(){$a--;if(0==$a&&(null!==ab&&(clearInterval(ab),ab=null),bb)){var a=bb;bb=null;a()}}function K(a){a="Aborted("+a+")";H(a);I=!0;Va=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");oa(a);throw a;}var db=a=>a.startsWith("data:application/octet-stream;base64,"),Ba=a=>a.startsWith("file://"),eb;
function fb(a){if(a==eb&&Ta)return new Uint8Array(Ta);if(za)return za(a);throw"both async and sync fetching of the wasm failed";}function gb(a){if(!Ta&&(qa||C)){if("function"==typeof fetch&&!Ba(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>fb(a));if(ya)return new Promise((b,c)=>{ya(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>fb(a))}
function hb(a,b,c){return gb(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{H(`failed to asynchronously prepare wasm: ${d}`);K(d)})}function ib(a,b){var c=eb;return Ta||"function"!=typeof WebAssembly.instantiateStreaming||db(c)||Ba(c)||D||"function"!=typeof fetch?hb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){H(`wasm streaming compile failed: ${f}`);H("falling back to ArrayBuffer instantiation");return hb(c,a,b)}))}
function Ja(){jb={O:kb,Aa:lb,b:mb,aa:nb,B:ob,qa:pb,Y:qb,_:rb,ra:sb,oa:tb,ha:ub,na:vb,L:wb,Z:xb,W:yb,pa:zb,X:Ab,va:Bb,F:Cb,Q:Db,P:Eb,E:Fb,u:Gb,q:Hb,G:Ib,A:Jb,R:Kb,ua:Lb,ka:Mb,U:Nb,ba:Ob,H:Pb,ja:La,ta:Qb,t:Rb,Ba:Sb,x:Tb,o:Ub,m:Vb,c:Wb,n:Xb,k:Yb,w:Zb,p:$b,f:ac,s:bc,l:cc,e:dc,j:ec,i:fc,g:gc,d:hc,ea:ic,fa:jc,ga:kc,ca:lc,da:mc,T:nc,h:oc,D:pc,I:qc,M:rc,y:sc,sa:tc,V:uc,v:vc,z:wc,N:xc,S:yc,za:zc,ya:Ac,la:Bc,ma:Cc,$:Dc,C:Ec,K:Fc,ia:Gc,J:Hc,a:l,xa:Ic,wa:Jc,r:Kc};return{a:jb}}
var Lc={916868:(a,b,c,d,f)=>{if("undefined"==typeof B||!B.Fb)return 1;a=L(Number(a>>>0));a.startsWith("./")&&(a=a.substring(2));a=B.Fb.get(a);if(!a)return 2;b=Number(b>>>0);c=Number(c>>>0);d=Number(d>>>0);if(b+c>a.byteLength)return 3;try{const g=a.subarray(b,b+c);switch(f){case 0:w().set(g,d>>>0);break;case 1:B.dc(d,g);break;default:return 4}return 0}catch{return 4}},917583:(a,b,c)=>{B.ec(a,w().subarray(b>>>0,b+c>>>0))},917646:()=>B.bc(),917687:a=>{B.Pb(a)},917723:()=>{B.Wb()},917754:()=>{B.Xb()},
917783:()=>{B.ac()},917808:a=>B.Vb(a),917841:a=>B.Zb(a),917873:(a,b,c)=>{B.Ob(Number(a),Number(b),Number(c),!0)},917936:(a,b,c)=>{B.Ob(Number(a),Number(b),Number(c))},917993:()=>"undefined"!==typeof wasmOffsetConverter,918050:a=>{B.kb("Abs",a,void 0)},918101:a=>{B.kb("Neg",a,void 0)},918152:a=>{B.kb("Floor",a,void 0)},918205:a=>{B.kb("Ceil",a,void 0)},918257:a=>{B.kb("Reciprocal",a,void 0)},918315:a=>{B.kb("Sqrt",a,void 0)},918367:a=>{B.kb("Exp",a,void 0)},918418:a=>{B.kb("Erf",a,void 0)},918469:a=>
{B.kb("Sigmoid",a,void 0)},918524:(a,b,c)=>{B.kb("HardSigmoid",a,{alpha:b,beta:c})},918603:a=>{B.kb("Log",a,void 0)},918654:a=>{B.kb("Sin",a,void 0)},918705:a=>{B.kb("Cos",a,void 0)},918756:a=>{B.kb("Tan",a,void 0)},918807:a=>{B.kb("Asin",a,void 0)},918859:a=>{B.kb("Acos",a,void 0)},918911:a=>{B.kb("Atan",a,void 0)},918963:a=>{B.kb("Sinh",a,void 0)},919015:a=>{B.kb("Cosh",a,void 0)},919067:a=>{B.kb("Asinh",a,void 0)},919120:a=>{B.kb("Acosh",a,void 0)},919173:a=>{B.kb("Atanh",a,void 0)},919226:a=>
{B.kb("Tanh",a,void 0)},919278:a=>{B.kb("Not",a,void 0)},919329:(a,b,c)=>{B.kb("Clip",a,{min:b,max:c})},919398:a=>{B.kb("Clip",a,void 0)},919450:(a,b)=>{B.kb("Elu",a,{alpha:b})},919508:a=>{B.kb("Gelu",a,void 0)},919560:a=>{B.kb("Relu",a,void 0)},919612:(a,b)=>{B.kb("LeakyRelu",a,{alpha:b})},919676:(a,b)=>{B.kb("ThresholdedRelu",a,{alpha:b})},919746:(a,b)=>{B.kb("Cast",a,{to:b})},919804:a=>{B.kb("Add",a,void 0)},919855:a=>{B.kb("Sub",a,void 0)},919906:a=>{B.kb("Mul",a,void 0)},919957:a=>{B.kb("Div",
a,void 0)},920008:a=>{B.kb("Pow",a,void 0)},920059:a=>{B.kb("Equal",a,void 0)},920112:a=>{B.kb("Greater",a,void 0)},920167:a=>{B.kb("GreaterOrEqual",a,void 0)},920229:a=>{B.kb("Less",a,void 0)},920281:a=>{B.kb("LessOrEqual",a,void 0)},920340:(a,b,c,d,f)=>{B.kb("ReduceMean",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},920515:(a,b,c,d,f)=>{B.kb("ReduceMax",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>
0)):[]})},920689:(a,b,c,d,f)=>{B.kb("ReduceMin",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},920863:(a,b,c,d,f)=>{B.kb("ReduceProd",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},921038:(a,b,c,d,f)=>{B.kb("ReduceSum",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},921212:(a,b,c,d,f)=>{B.kb("ReduceL1",a,{keepDims:!!b,noopWithEmptyAxes:!!c,
axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},921385:(a,b,c,d,f)=>{B.kb("ReduceL2",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},921558:(a,b,c,d,f)=>{B.kb("ReduceLogSum",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},921735:(a,b,c,d,f)=>{B.kb("ReduceSumSquare",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},
921915:(a,b,c,d,f)=>{B.kb("ReduceLogSumExp",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},922095:a=>{B.kb("Where",a,void 0)},922148:(a,b,c)=>{B.kb("Transpose",a,{perm:b?Array.from(z().subarray(Number(b)>>>0,Number(c)>>>0)):[]})},922272:(a,b,c,d)=>{B.kb("DepthToSpace",a,{blocksize:b,mode:L(c),format:d?"NHWC":"NCHW"})},922405:(a,b,c,d)=>{B.kb("DepthToSpace",a,{blocksize:b,mode:L(c),format:d?"NHWC":"NCHW"})},922538:(a,b,c,d,f,g,k,m,p,n,r,v,x,
h,u)=>{B.kb("ConvTranspose",a,{format:p?"NHWC":"NCHW",autoPad:b,dilations:[c],group:d,kernelShape:[f],pads:[g,k],strides:[m],wIsConst:()=>!!e()[n>>>0],outputPadding:r?Array.from(z().subarray(Number(r)>>>0,Number(v)>>>0)):[],outputShape:x?Array.from(z().subarray(Number(x)>>>0,Number(h)>>>0)):[],activation:L(u)})},922971:(a,b,c,d,f,g,k,m,p,n,r,v,x,h)=>{B.kb("ConvTranspose",a,{format:m?"NHWC":"NCHW",autoPad:b,dilations:Array.from(z().subarray(Number(c)>>>0,(Number(c)>>>0)+2>>>0)),group:d,kernelShape:Array.from(z().subarray(Number(f)>>>
0,(Number(f)>>>0)+2>>>0)),pads:Array.from(z().subarray(Number(g)>>>0,(Number(g)>>>0)+4>>>0)),strides:Array.from(z().subarray(Number(k)>>>0,(Number(k)>>>0)+2>>>0)),wIsConst:()=>!!e()[p>>>0],outputPadding:n?Array.from(z().subarray(Number(n)>>>0,Number(r)>>>0)):[],outputShape:v?Array.from(z().subarray(Number(v)>>>0,Number(x)>>>0)):[],activation:L(h)})},923632:(a,b,c,d,f,g,k,m,p,n,r,v,x,h,u)=>{B.kb("ConvTranspose",a,{format:p?"NHWC":"NCHW",autoPad:b,dilations:[c],group:d,kernelShape:[f],pads:[g,k],strides:[m],
wIsConst:()=>!!e()[n>>>0],outputPadding:r?Array.from(z().subarray(Number(r)>>>0,Number(v)>>>0)):[],outputShape:x?Array.from(z().subarray(Number(x)>>>0,Number(h)>>>0)):[],activation:L(u)})},924065:(a,b,c,d,f,g,k,m,p,n,r,v,x,h)=>{B.kb("ConvTranspose",a,{format:m?"NHWC":"NCHW",autoPad:b,dilations:Array.from(z().subarray(Number(c)>>>0,(Number(c)>>>0)+2>>>0)),group:d,kernelShape:Array.from(z().subarray(Number(f)>>>0,(Number(f)>>>0)+2>>>0)),pads:Array.from(z().subarray(Number(g)>>>0,(Number(g)>>>0)+4>>>
0)),strides:Array.from(z().subarray(Number(k)>>>0,(Number(k)>>>0)+2>>>0)),wIsConst:()=>!!e()[p>>>0],outputPadding:n?Array.from(z().subarray(Number(n)>>>0,Number(r)>>>0)):[],outputShape:v?Array.from(z().subarray(Number(v)>>>0,Number(x)>>>0)):[],activation:L(h)})},924726:(a,b)=>{B.kb("GlobalAveragePool",a,{format:b?"NHWC":"NCHW"})},924817:(a,b,c,d,f,g,k,m,p,n,r,v,x,h)=>{B.kb("AveragePool",a,{format:h?"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:d,storage_order:f,dilations:g?Array.from(z().subarray(Number(g)>>>
0,Number(k)>>>0)):[],kernel_shape:m?Array.from(z().subarray(Number(m)>>>0,Number(p)>>>0)):[],pads:n?Array.from(z().subarray(Number(n)>>>0,Number(r)>>>0)):[],strides:v?Array.from(z().subarray(Number(v)>>>0,Number(x)>>>0)):[]})},925296:(a,b)=>{B.kb("GlobalAveragePool",a,{format:b?"NHWC":"NCHW"})},925387:(a,b,c,d,f,g,k,m,p,n,r,v,x,h)=>{B.kb("AveragePool",a,{format:h?"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:d,storage_order:f,dilations:g?Array.from(z().subarray(Number(g)>>>0,Number(k)>>>
0)):[],kernel_shape:m?Array.from(z().subarray(Number(m)>>>0,Number(p)>>>0)):[],pads:n?Array.from(z().subarray(Number(n)>>>0,Number(r)>>>0)):[],strides:v?Array.from(z().subarray(Number(v)>>>0,Number(x)>>>0)):[]})},925866:(a,b)=>{B.kb("GlobalMaxPool",a,{format:b?"NHWC":"NCHW"})},925953:(a,b,c,d,f,g,k,m,p,n,r,v,x,h)=>{B.kb("MaxPool",a,{format:h?"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:d,storage_order:f,dilations:g?Array.from(z().subarray(Number(g)>>>0,Number(k)>>>0)):[],kernel_shape:m?
Array.from(z().subarray(Number(m)>>>0,Number(p)>>>0)):[],pads:n?Array.from(z().subarray(Number(n)>>>0,Number(r)>>>0)):[],strides:v?Array.from(z().subarray(Number(v)>>>0,Number(x)>>>0)):[]})},926428:(a,b)=>{B.kb("GlobalMaxPool",a,{format:b?"NHWC":"NCHW"})},926515:(a,b,c,d,f,g,k,m,p,n,r,v,x,h)=>{B.kb("MaxPool",a,{format:h?"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:d,storage_order:f,dilations:g?Array.from(z().subarray(Number(g)>>>0,Number(k)>>>0)):[],kernel_shape:m?Array.from(z().subarray(Number(m)>>>
0,Number(p)>>>0)):[],pads:n?Array.from(z().subarray(Number(n)>>>0,Number(r)>>>0)):[],strides:v?Array.from(z().subarray(Number(v)>>>0,Number(x)>>>0)):[]})},926990:(a,b,c,d,f)=>{B.kb("Gemm",a,{alpha:b,beta:c,transA:d,transB:f})},927094:a=>{B.kb("MatMul",a,void 0)},927148:(a,b,c,d)=>{B.kb("ArgMax",a,{keepDims:!!b,selectLastIndex:!!c,axis:d})},927256:(a,b,c,d)=>{B.kb("ArgMin",a,{keepDims:!!b,selectLastIndex:!!c,axis:d})},927364:(a,b)=>{B.kb("Softmax",a,{axis:b})},927427:(a,b)=>{B.kb("Concat",a,{axis:b})},
927487:(a,b,c,d,f)=>{B.kb("Split",a,{axis:b,numOutputs:c,splitSizes:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},927643:a=>{B.kb("Expand",a,void 0)},927697:(a,b)=>{B.kb("Gather",a,{axis:Number(b)})},927768:(a,b)=>{B.kb("GatherElements",a,{axis:Number(b)})},927847:(a,b)=>{B.kb("GatherND",a,{batch_dims:Number(b)})},927926:(a,b,c,d,f,g,k,m,p,n,r)=>{B.kb("Resize",a,{antialias:b,axes:c?Array.from(z().subarray(Number(c)>>>0,Number(d)>>>0)):[],coordinateTransformMode:L(f),cubicCoeffA:g,
excludeOutside:k,extrapolationValue:m,keepAspectRatioPolicy:L(p),mode:L(n),nearestMode:L(r)})},928288:(a,b,c,d,f,g,k)=>{B.kb("Slice",a,{starts:b?Array.from(z().subarray(Number(b)>>>0,Number(c)>>>0)):[],ends:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[],axes:g?Array.from(z().subarray(Number(g)>>>0,Number(k)>>>0)):[]})},928552:a=>{B.kb("Tile",a,void 0)},928604:(a,b,c)=>{B.kb("InstanceNormalization",a,{epsilon:b,format:c?"NHWC":"NCHW"})},928718:(a,b,c)=>{B.kb("InstanceNormalization",a,{epsilon:b,
format:c?"NHWC":"NCHW"})},928832:a=>{B.kb("Range",a,void 0)},928885:(a,b)=>{B.kb("Einsum",a,{equation:L(b)})},928966:(a,b,c,d,f)=>{B.kb("Pad",a,{mode:b,value:c,pads:d?Array.from(z().subarray(Number(d)>>>0,Number(f)>>>0)):[]})},929109:(a,b,c,d,f,g)=>{B.kb("BatchNormalization",a,{epsilon:b,momentum:c,spatial:!!f,trainingMode:!!d,format:g?"NHWC":"NCHW"})},929278:(a,b,c,d,f,g)=>{B.kb("BatchNormalization",a,{epsilon:b,momentum:c,spatial:!!f,trainingMode:!!d,format:g?"NHWC":"NCHW"})},929447:(a,b,c)=>{B.kb("CumSum",
a,{exclusive:Number(b),reverse:Number(c)})},929544:(a,b,c)=>{B.kb("DequantizeLinear",a,{axis:b,blockSize:c})},929634:(a,b,c,d,f)=>{B.kb("GridSample",a,{align_corners:b,mode:L(c),padding_mode:L(d),format:f?"NHWC":"NCHW"})},929804:(a,b,c,d,f)=>{B.kb("GridSample",a,{align_corners:b,mode:L(c),padding_mode:L(d),format:f?"NHWC":"NCHW"})},929974:(a,b,c,d,f,g,k,m,p)=>{B.kb("Attention",a,{numHeads:b,isUnidirectional:c,maskFilterValue:d,scale:f,doRotary:g,qkvHiddenSizes:k?Array.from(z().subarray(Number(m)>>>
0,Number(m)+k>>>0)):[],pastPresentShareBuffer:!!p})},930246:a=>{B.kb("BiasAdd",a,void 0)},930301:a=>{B.kb("BiasSplitGelu",a,void 0)},930362:a=>{B.kb("FastGelu",a,void 0)},930418:(a,b,c,d,f,g,k,m,p,n,r,v,x,h,u,y)=>{B.kb("Conv",a,{format:v?"NHWC":"NCHW",auto_pad:b,dilations:c?Array.from(z().subarray(Number(c)>>>0,Number(d)>>>0)):[],group:f,kernel_shape:g?Array.from(z().subarray(Number(g)>>>0,Number(k)>>>0)):[],pads:m?Array.from(z().subarray(Number(m)>>>0,Number(p)>>>0)):[],strides:n?Array.from(z().subarray(Number(n)>>>
0,Number(r)>>>0)):[],w_is_const:()=>!!e()[Number(x)>>>0],activation:L(h),activation_params:u?Array.from(ja().subarray(Number(u)>>>0,Number(y)>>>0)):[]})},931002:a=>{B.kb("Gelu",a,void 0)},931054:(a,b,c,d,f,g,k,m,p)=>{B.kb("GroupQueryAttention",a,{numHeads:b,kvNumHeads:c,scale:d,softcap:f,doRotary:g,rotaryInterleaved:k,smoothSoftmax:m,localWindowSize:p})},931271:(a,b,c,d)=>{B.kb("LayerNormalization",a,{axis:b,epsilon:c,simplified:!!d})},931382:(a,b,c,d)=>{B.kb("LayerNormalization",a,{axis:b,epsilon:c,
simplified:!!d})},931493:(a,b,c,d,f,g)=>{B.kb("MatMulNBits",a,{k:b,n:c,accuracyLevel:d,bits:f,blockSize:g})},931620:(a,b,c,d,f,g)=>{B.kb("MultiHeadAttention",a,{numHeads:b,isUnidirectional:c,maskFilterValue:d,scale:f,doRotary:g})},931779:(a,b)=>{B.kb("QuickGelu",a,{alpha:b})},931843:(a,b,c,d,f)=>{B.kb("RotaryEmbedding",a,{interleaved:!!b,numHeads:c,rotaryEmbeddingDim:d,scale:f})},931982:(a,b,c)=>{B.kb("SkipLayerNormalization",a,{epsilon:b,simplified:!!c})},932084:(a,b,c)=>{B.kb("SkipLayerNormalization",
a,{epsilon:b,simplified:!!c})},932186:(a,b,c,d)=>{B.kb("GatherBlockQuantized",a,{gatherAxis:b,quantizeAxis:c,blockSize:d})},932307:a=>{B.$b(a)},932341:(a,b)=>B.cc(Number(a),Number(b),B.Gb.hc,B.Gb.errors)};function lb(a,b,c){return Mc(async()=>{await B.Yb(Number(a),Number(b),Number(c))})}function kb(){return"undefined"!==typeof wasmOffsetConverter}function Nc(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Oc=a=>{a.terminate();a.onmessage=()=>{}},Rc=a=>{0==M.length&&(Pc(),Qc(M[0]));var b=M.pop();if(!b)return 6;N.push(b);O[a.Bb]=b;b.Bb=a.Bb;var c={cmd:"run",start_routine:a.ic,arg:a.Rb,pthread_ptr:a.Bb};D&&b.unref();b.postMessage(c,a.nc);return 0},Sc=0,P=(a,b,...c)=>{for(var d=2*c.length,f=Tc(),g=Vc(8*d),k=g>>>3,m=0;m<c.length;m++){var p=c[m];"bigint"==typeof p?(J[k+2*m]=1n,J[k+2*m+1]=p):(J[k+2*m]=0n,la()[k+2*m+1>>>0]=p)}a=Wc(a,0,d,g,b);Xc(f);return a};
function Ic(a){if(E)return P(0,1,a);Va=a;if(!(0<Sc)){for(var b of N)Oc(b);for(b of M)Oc(b);M=[];N=[];O=[];I=!0}wa(a,new Nc(a))}function Yc(a){if(E)return P(1,0,a);Dc(a)}var Dc=a=>{Va=a;if(E)throw Yc(a),"unwind";Ic(a)},M=[],N=[],Zc=[],O={};function $c(){for(var a=B.numThreads-1;a--;)Pc();Xa.unshift(()=>{$a++;ad(()=>cb())})}var cd=a=>{var b=a.Bb;delete O[b];M.push(a);N.splice(N.indexOf(a),1);a.Bb=0;bd(b)};function Na(){Zc.forEach(a=>a())}
var Qc=a=>new Promise(b=>{a.onmessage=g=>{g=g.data;var k=g.cmd;if(g.targetThread&&g.targetThread!=Ia()){var m=O[g.targetThread];m?m.postMessage(g,g.transferList):H(`Internal error! Worker sent a message "${k}" to target pthread ${g.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===k)Ra();else if("spawnThread"===k)Rc(g);else if("cleanupThread"===k)cd(O[g.thread]);else if("killThread"===k)g=g.thread,k=O[g],delete O[g],Oc(k),bd(g),N.splice(N.indexOf(k),1),k.Bb=0;else if("cancelThread"===
k)O[g.thread].postMessage({cmd:"cancel"});else if("loaded"===k)a.loaded=!0,D&&!a.Bb&&a.unref(),b(a);else if("alert"===k)alert(`Thread ${g.threadId}: ${g.text}`);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===k)B[g.handler](...g.args);else k&&H(`worker sent an unknown command ${k}`)};a.onerror=g=>{H(`${"worker sent an error!"} ${g.filename}:${g.lineno}: ${g.message}`);throw g;};D&&(a.on("message",g=>a.onmessage({data:g})),a.on("error",g=>a.onerror(g)));var c=[],d=[],f;for(f of d)B.hasOwnProperty(f)&&
c.push(f);a.postMessage({cmd:"load",handlers:c,wasmMemory:l,wasmModule:Ua})});function ad(a){E?a():Promise.all(M.map(Qc)).then(a)}function Pc(){var a=new Worker(new URL(import.meta.url),{type:"module",workerData:"em-pthread",name:"em-pthread"});M.push(a)}var dd=a=>{for(;0<a.length;)a.shift()(B)},Ma=()=>{var a=Ia(),b=A()[a+52>>>2>>>0];a=A()[a+56>>>2>>>0];ed(b,b-a);Xc(b)},Pa=(a,b)=>{Sc=0;a=fd(a,b);0<Sc?Va=a:Qa(a)};class gd{constructor(a){this.Kb=a-24}}var hd=0,jd=0;
function mb(a,b,c){a>>>=0;var d=new gd(a);b>>>=0;c>>>=0;A()[d.Kb+16>>>2>>>0]=0;A()[d.Kb+4>>>2>>>0]=b;A()[d.Kb+8>>>2>>>0]=c;hd=a;jd++;throw hd;}function kd(a,b,c,d){return E?P(2,1,a,b,c,d):nb(a,b,c,d)}
function nb(a,b,c,d){a>>>=0;b>>>=0;c>>>=0;d>>>=0;if("undefined"==typeof SharedArrayBuffer)return H("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[];if(E&&0===f.length)return kd(a,b,c,d);a={ic:c,Bb:a,Rb:d,nc:f};return E?(a.Nb="spawnThread",postMessage(a,f),0):Rc(a)}
var ld="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,md=(a,b,c)=>{b>>>=0;var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ld)return ld.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>
10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d},L=(a,b)=>(a>>>=0)?md(w(),a,b):"";function ob(a,b,c){return E?P(3,1,a,b,c):0}function pb(a,b){if(E)return P(4,1,a,b)}
var nd=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},od=(a,b,c,d)=>{c>>>=0;if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++>>>0]=k}else{if(2047>=k){if(c+1>=d)break;b[c++>>>0]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++>>>0]=224|k>>12}else{if(c+3>=d)break;b[c++>>>0]=240|k>>
18;b[c++>>>0]=128|k>>12&63}b[c++>>>0]=128|k>>6&63}b[c++>>>0]=128|k&63}}b[c>>>0]=0;return c-f},pd=(a,b,c)=>od(a,w(),b,c);function qb(a,b){if(E)return P(5,1,a,b)}function rb(a,b,c){if(E)return P(6,1,a,b,c)}function sb(a,b,c){return E?P(7,1,a,b,c):0}function tb(a,b){if(E)return P(8,1,a,b)}function ub(a,b,c){if(E)return P(9,1,a,b,c)}function vb(a,b,c,d){if(E)return P(10,1,a,b,c,d)}function wb(a,b,c,d){if(E)return P(11,1,a,b,c,d)}function xb(a,b,c,d){if(E)return P(12,1,a,b,c,d)}
function yb(a){if(E)return P(13,1,a)}function zb(a,b){if(E)return P(14,1,a,b)}function Ab(a,b,c){if(E)return P(15,1,a,b,c)}var Bb=()=>{K("")},qd,Q=a=>{for(var b="";w()[a>>>0];)b+=qd[w()[a++>>>0]];return b},rd={},sd={},td={},R;
function ud(a,b,c={}){var d=b.name;if(!a)throw new R(`type "${d}" must have a positive integer typeid pointer`);if(sd.hasOwnProperty(a)){if(c.Tb)return;throw new R(`Cannot register type '${d}' twice`);}sd[a]=b;delete td[a];rd.hasOwnProperty(a)&&(b=rd[a],delete rd[a],b.forEach(f=>f()))}function S(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return ud(a,b,c)}
var vd=(a,b,c)=>{switch(b){case 1:return c?d=>e()[d>>>0]:d=>w()[d>>>0];case 2:return c?d=>ca()[d>>>1>>>0]:d=>ea()[d>>>1>>>0];case 4:return c?d=>z()[d>>>2>>>0]:d=>A()[d>>>2>>>0];case 8:return c?d=>J[d>>>3]:d=>Wa[d>>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}};
function Cb(a,b,c){a>>>=0;c>>>=0;b=Q(b>>>0);S(a,{name:b,fromWireType:d=>d,toWireType:function(d,f){if("bigint"!=typeof f&&"number"!=typeof f)throw null===f?f="null":(d=typeof f,f="object"===d||"array"===d||"function"===d?f.toString():""+f),new TypeError(`Cannot convert "${f}" to ${this.name}`);"number"==typeof f&&(f=BigInt(f));return f},argPackAdvance:T,readValueFromPointer:vd(b,c,-1==b.indexOf("u")),Eb:null})}var T=8;
function Db(a,b,c,d){a>>>=0;b=Q(b>>>0);S(a,{name:b,fromWireType:function(f){return!!f},toWireType:function(f,g){return g?c:d},argPackAdvance:T,readValueFromPointer:function(f){return this.fromWireType(w()[f>>>0])},Eb:null})}var wd=[],U=[];function Wb(a){a>>>=0;9<a&&0===--U[a+1]&&(U[a]=void 0,wd.push(a))}
var V=a=>{if(!a)throw new R("Cannot use deleted val. handle = "+a);return U[a]},W=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=wd.pop()||U.length;U[b]=a;U[b+1]=1;return b}};function xd(a){return this.fromWireType(A()[a>>>2>>>0])}var yd={name:"emscripten::val",fromWireType:a=>{var b=V(a);Wb(a);return b},toWireType:(a,b)=>W(b),argPackAdvance:T,readValueFromPointer:xd,Eb:null};function Eb(a){return S(a>>>0,yd)}
var zd=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ja()[c>>>2>>>0])};case 8:return function(c){return this.fromWireType(la()[c>>>3>>>0])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}};function Fb(a,b,c){a>>>=0;c>>>=0;b=Q(b>>>0);S(a,{name:b,fromWireType:d=>d,toWireType:(d,f)=>f,argPackAdvance:T,readValueFromPointer:zd(b,c),Eb:null})}
function Gb(a,b,c,d,f){a>>>=0;c>>>=0;b=Q(b>>>0);-1===f&&(f=4294967295);f=m=>m;if(0===d){var g=32-8*c;f=m=>m<<g>>>g}var k=b.includes("unsigned")?function(m,p){return p>>>0}:function(m,p){return p};S(a,{name:b,fromWireType:f,toWireType:k,argPackAdvance:T,readValueFromPointer:vd(b,c,0!==d),Eb:null})}
function Hb(a,b,c){function d(g){var k=A()[g>>>2>>>0];g=A()[g+4>>>2>>>0];return new f(e().buffer,g,k)}a>>>=0;var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=Q(c>>>0);S(a,{name:c,fromWireType:d,argPackAdvance:T,readValueFromPointer:d},{Tb:!0})}
function Ib(a,b){a>>>=0;b=Q(b>>>0);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var f=A()[d>>>2>>>0],g=d+4;if(c)for(var k=g,m=0;m<=f;++m){var p=g+m;if(m==f||0==w()[p>>>0]){k=L(k,p-k);if(void 0===n)var n=k;else n+=String.fromCharCode(0),n+=k;k=p+1}}else{n=Array(f);for(m=0;m<f;++m)n[m]=String.fromCharCode(w()[g+m>>>0]);n=n.join("")}X(d);return n},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"==typeof f;if(!(g||f instanceof Uint8Array||f instanceof
Uint8ClampedArray||f instanceof Int8Array))throw new R("Cannot pass non-string to std::string");var k=c&&g?nd(f):f.length;var m=Ad(4+k+1),p=m+4;A()[m>>>2>>>0]=k;if(c&&g)pd(f,p,k+1);else if(g)for(g=0;g<k;++g){var n=f.charCodeAt(g);if(255<n)throw X(p),new R("String has UTF-16 code units that do not fit in 8 bits");w()[p+g>>>0]=n}else for(g=0;g<k;++g)w()[p+g>>>0]=f[g];null!==d&&d.push(X,m);return m},argPackAdvance:T,readValueFromPointer:xd,Eb(d){X(d)}})}
var Bd="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Cd=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ea()[c>>>0];)++c;c<<=1;if(32<c-a&&Bd)return Bd.decode(w().slice(a,c));c="";for(d=0;!(d>=b/2);++d){var f=ca()[a+2*d>>>1>>>0];if(0==f)break;c+=String.fromCharCode(f)}return c},Dd=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f){var g=a.charCodeAt(f);ca()[b>>>1>>>0]=g;b+=2}ca()[b>>>1>>>0]=0;return b-d},Ed=a=>2*a.length,Fd=(a,b)=>
{for(var c=0,d="";!(c>=b/4);){var f=z()[a+4*c>>>2>>>0];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d},Gd=(a,b,c)=>{b>>>=0;c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}z()[b>>>2>>>0]=g;b+=4;if(b+4>c)break}z()[b>>>2>>>0]=0;return b-d},Hd=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=
d&&57343>=d&&++c;b+=4}return b};
function Jb(a,b,c){a>>>=0;b>>>=0;c>>>=0;c=Q(c);if(2===b){var d=Cd;var f=Dd;var g=Ed;var k=m=>ea()[m>>>1>>>0]}else 4===b&&(d=Fd,f=Gd,g=Hd,k=m=>A()[m>>>2>>>0]);S(a,{name:c,fromWireType:m=>{for(var p=A()[m>>>2>>>0],n,r=m+4,v=0;v<=p;++v){var x=m+4+v*b;if(v==p||0==k(x))r=d(r,x-r),void 0===n?n=r:(n+=String.fromCharCode(0),n+=r),r=x+b}X(m);return n},toWireType:(m,p)=>{if("string"!=typeof p)throw new R(`Cannot pass non-string to C++ string type ${c}`);var n=g(p),r=Ad(4+n+b);A()[r>>>2>>>0]=n/b;f(p,r+4,n+b);
null!==m&&m.push(X,r);return r},argPackAdvance:T,readValueFromPointer:xd,Eb(m){X(m)}})}function Kb(a,b){a>>>=0;b=Q(b>>>0);S(a,{Ub:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})}var Lb=()=>1;function Mb(a){Ka(a>>>0,!C,1,!qa,131072,!1);Na()}var Id=a=>{if(!I)try{if(a(),!(0<Sc))try{E?Qa(Va):Dc(Va)}catch(b){b instanceof Nc||"unwind"==b||wa(1,b)}}catch(b){b instanceof Nc||"unwind"==b||wa(1,b)}};
function La(a){a>>>=0;"function"===typeof Atomics.oc&&(Atomics.oc(z(),a>>>2,a).value.then(Ra),a+=128,Atomics.store(z(),a>>>2,1))}var Ra=()=>{var a=Ia();a&&(La(a),Id(Jd))};function Nb(a,b){a>>>=0;a==b>>>0?setTimeout(Ra):E?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=O[a])&&a.postMessage({cmd:"checkMailbox"})}var Kd=[];function Ob(a,b,c,d,f){b>>>=0;d/=2;Kd.length=d;c=f>>>0>>>3;for(f=0;f<d;f++)Kd[f]=J[c+2*f]?J[c+2*f+1]:la()[c+2*f+1>>>0];return(b?Lc[b]:Ld[a])(...Kd)}
function Pb(a){a>>>=0;E?postMessage({cmd:"cleanupThread",thread:a}):cd(O[a])}function Qb(a){D&&O[a>>>0].ref()}var Nd=(a,b)=>{var c=sd[a];if(void 0===c)throw a=Md(a),c=Q(a),X(a),new R(`${b} has unknown type ${c}`);return c},Od=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(A()[b>>>2>>>0]=W(d));return a};function Rb(a,b,c){b>>>=0;c>>>=0;a=V(a>>>0);b=Nd(b,"emval::as");return Od(b,c,a)}function Sb(a,b){b>>>=0;a=V(a>>>0);b=Nd(b,"emval::as");return b.toWireType(null,a)}var Pd=a=>{try{a()}catch(b){K(b)}};
function Qd(){var a=Y,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...f)=>{Rd.push(c);try{return d(...f)}finally{I||(Rd.pop(),F&&1===Z&&0===Rd.length&&(Z=0,Sc+=1,Pd(Sd),"undefined"!=typeof Fibers&&Fibers.tc()))}}:d;return b}var Z=0,F=null,Td=0,Rd=[],Ud={},Vd={},Wd=0,Xd=null,Yd=[];function sa(){return new Promise((a,b)=>{Xd={resolve:a,reject:b}})}
function Zd(){var a=Ad(65548),b=a+12;A()[a>>>2>>>0]=b;A()[a+4>>>2>>>0]=b+65536;b=Rd[0];var c=Ud[b];void 0===c&&(c=Wd++,Ud[b]=c,Vd[c]=b);b=c;z()[a+8>>>2>>>0]=b;return a}function $d(){var a=z()[F+8>>>2>>>0];a=Y[Vd[a]];--Sc;return a()}
function ae(a){if(!I){if(0===Z){var b=!1,c=!1;a((d=0)=>{if(!I&&(Td=d,b=!0,c)){Z=2;Pd(()=>be(F));"undefined"!=typeof Browser&&Browser.Lb.Sb&&Browser.Lb.resume();d=!1;try{var f=$d()}catch(m){f=m,d=!0}var g=!1;if(!F){var k=Xd;k&&(Xd=null,(d?k.reject:k.resolve)(f),g=!0)}if(d&&!g)throw f;}});c=!0;b||(Z=1,F=Zd(),"undefined"!=typeof Browser&&Browser.Lb.Sb&&Browser.Lb.pause(),Pd(()=>ce(F)))}else 2===Z?(Z=0,Pd(de),X(F),F=null,Yd.forEach(Id)):K(`invalid state: ${Z}`);return Td}}
function Mc(a){return ae(b=>{a().then(b)})}function Tb(a){a>>>=0;return Mc(()=>{a=V(a);return a.then(W)})}var ee=[];function Ub(a,b,c,d){c>>>=0;d>>>=0;a=ee[a>>>0];b=V(b>>>0);return a(null,b,c,d)}var fe={},ge=a=>{var b=fe[a];return void 0===b?Q(a):b};function Vb(a,b,c,d,f){c>>>=0;d>>>=0;f>>>=0;a=ee[a>>>0];b=V(b>>>0);c=ge(c);return a(b,b[c],d,f)}var he=()=>"object"==typeof globalThis?globalThis:Function("return this")();function Xb(a){a>>>=0;if(0===a)return W(he());a=ge(a);return W(he()[a])}
var ie=a=>{var b=ee.length;ee.push(a);return b},je=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Nd(A()[b+4*d>>>2>>>0],"parameter "+d);return c},ke=(a,b)=>Object.defineProperty(b,"name",{value:a});function le(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=ke(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Yb(a,b,c){b=je(a,b>>>0);var d=b.shift();a--;var f="return function (obj, func, destructorsRef, args) {\n",g=0,k=[];0===c&&k.push("obj");for(var m=["retType"],p=[d],n=0;n<a;++n)k.push("arg"+n),m.push("argType"+n),p.push(b[n]),f+=`  var arg${n} = argType${n}.readValueFromPointer(args${g?"+"+g:""});\n`,g+=b[n].argPackAdvance;f+=`  var rv = ${1===c?"new func":"func.call"}(${k.join(", ")});\n`;d.Ub||(m.push("emval_returnValue"),p.push(Od),f+="  return emval_returnValue(retType, destructorsRef, rv);\n");
m.push(f+"};\n");a=le(m)(...p);c=`methodCaller<(${b.map(r=>r.name).join(", ")}) => ${d.name}>`;return ie(ke(c,a))}function Zb(a){a=ge(a>>>0);return W(B[a])}function $b(a,b){b>>>=0;a=V(a>>>0);b=V(b);return W(a[b])}function ac(a){a>>>=0;9<a&&(U[a+1]+=1)}function bc(){return W([])}function cc(a){a=V(a>>>0);for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return W(b)}function dc(a){return W(ge(a>>>0))}function ec(){return W({})}
function fc(a){a>>>=0;for(var b=V(a);b.length;){var c=b.pop();b.pop()(c)}Wb(a)}function gc(a,b,c){b>>>=0;c>>>=0;a=V(a>>>0);b=V(b);c=V(c);a[b]=c}function hc(a,b){b>>>=0;a=Nd(a>>>0,"_emval_take_value");a=a.readValueFromPointer(b);return W(a)}
function ic(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);z()[b>>>2>>>0]=a.getUTCSeconds();z()[b+4>>>2>>>0]=a.getUTCMinutes();z()[b+8>>>2>>>0]=a.getUTCHours();z()[b+12>>>2>>>0]=a.getUTCDate();z()[b+16>>>2>>>0]=a.getUTCMonth();z()[b+20>>>2>>>0]=a.getUTCFullYear()-1900;z()[b+24>>>2>>>0]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;z()[b+28>>>2>>>0]=a}
var me=a=>0===a%4&&(0!==a%100||0===a%400),ne=[0,31,60,91,121,152,182,213,244,274,305,335],oe=[0,31,59,90,120,151,181,212,243,273,304,334];
function jc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);z()[b>>>2>>>0]=a.getSeconds();z()[b+4>>>2>>>0]=a.getMinutes();z()[b+8>>>2>>>0]=a.getHours();z()[b+12>>>2>>>0]=a.getDate();z()[b+16>>>2>>>0]=a.getMonth();z()[b+20>>>2>>>0]=a.getFullYear()-1900;z()[b+24>>>2>>>0]=a.getDay();var c=(me(a.getFullYear())?ne:oe)[a.getMonth()]+a.getDate()-1|0;z()[b+28>>>2>>>0]=c;z()[b+36>>>2>>>0]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();
var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;z()[b+32>>>2>>>0]=a}
function kc(a){a>>>=0;var b=new Date(z()[a+20>>>2>>>0]+1900,z()[a+16>>>2>>>0],z()[a+12>>>2>>>0],z()[a+8>>>2>>>0],z()[a+4>>>2>>>0],z()[a>>>2>>>0],0),c=z()[a+32>>>2>>>0],d=b.getTimezoneOffset(),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),k=Math.min(g,f);0>c?z()[a+32>>>2>>>0]=Number(f!=g&&k==d):0<c!=(k==d)&&(f=Math.max(g,f),b.setTime(b.getTime()+6E4*((0<c?k:f)-d)));z()[a+24>>>2>>>0]=b.getDay();c=(me(b.getFullYear())?ne:oe)[b.getMonth()]+
b.getDate()-1|0;z()[a+28>>>2>>>0]=c;z()[a>>>2>>>0]=b.getSeconds();z()[a+4>>>2>>>0]=b.getMinutes();z()[a+8>>>2>>>0]=b.getHours();z()[a+12>>>2>>>0]=b.getDate();z()[a+16>>>2>>>0]=b.getMonth();z()[a+20>>>2>>>0]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)}function lc(a,b,c,d,f,g,k){return E?P(16,1,a,b,c,d,f,g,k):-52}function mc(a,b,c,d,f,g){if(E)return P(17,1,a,b,c,d,f,g)}
function nc(a,b,c,d){a>>>=0;b>>>=0;c>>>=0;d>>>=0;var f=(new Date).getFullYear(),g=new Date(f,0,1),k=new Date(f,6,1);f=g.getTimezoneOffset();var m=k.getTimezoneOffset(),p=Math.max(f,m);A()[a>>>2>>>0]=60*p;z()[b>>>2>>>0]=Number(f!=m);a=n=>n.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];g=a(g);k=a(k);m<f?(pd(g,c,17),pd(k,d,17)):(pd(g,d,17),pd(k,c,17))}
var pe=[],qe=(a,b)=>{pe.length=0;for(var c;c=w()[a++>>>0];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;pe.push(112==c?A()[b>>>2>>>0]:106==c?J[b>>>3]:105==c?z()[b>>>2>>>0]:la()[b>>>3>>>0]);b+=d?8:4}return pe};function oc(a,b,c){a>>>=0;b=qe(b>>>0,c>>>0);return Lc[a](...b)}function pc(a,b,c){a>>>=0;b=qe(b>>>0,c>>>0);return Lc[a](...b)}var qc=()=>{},rc=()=>Date.now();function sc(a,b){return H(L(a>>>0,b>>>0))}var tc=()=>{Sc+=1;throw"unwind";};function uc(){return 4294901760}var vc;
vc=()=>performance.timeOrigin+performance.now();var wc=()=>D?require("os").cpus().length:navigator.hardwareConcurrency;function xc(){K("Cannot use emscripten_pc_get_function without -sUSE_OFFSET_CONVERTER");return 0}
function yc(a){a>>>=0;var b=w().length;if(a<=b||4294901760<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var f=Math;d=Math.max(a,d);a:{f=(f.min.call(f,4294901760,d+(65536-d%65536)%65536)-l.buffer.byteLength+65535)/65536;try{l.grow(f);t();var g=1;break a}catch(k){}g=void 0}if(g)return!0}return!1}var re=()=>{K("Cannot use convertFrameToPC (needed by __builtin_return_address) without -sUSE_OFFSET_CONVERTER");return 0},se={},te=a=>{a.forEach(b=>{var c=re();c&&(se[c]=b)})};
function zc(){var a=Error().stack.toString().split("\n");"Error"==a[0]&&a.shift();te(a);se.Qb=re();se.fc=a;return se.Qb}function Ac(a,b,c){a>>>=0;b>>>=0;if(se.Qb==a)var d=se.fc;else d=Error().stack.toString().split("\n"),"Error"==d[0]&&d.shift(),te(d);for(var f=3;d[f]&&re()!=a;)++f;for(a=0;a<c&&d[a+f];++a)z()[b+4*a>>>2>>>0]=re();return a}
var ue={},we=()=>{if(!ve){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:va||"./this.program"},b;for(b in ue)void 0===ue[b]?delete a[b]:a[b]=ue[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ve=c}return ve},ve;
function Bc(a,b){if(E)return P(18,1,a,b);a>>>=0;b>>>=0;var c=0;we().forEach((d,f)=>{var g=b+c;f=A()[a+4*f>>>2>>>0]=g;for(g=0;g<d.length;++g)e()[f++>>>0]=d.charCodeAt(g);e()[f>>>0]=0;c+=d.length+1});return 0}function Cc(a,b){if(E)return P(19,1,a,b);a>>>=0;b>>>=0;var c=we();A()[a>>>2>>>0]=c.length;var d=0;c.forEach(f=>d+=f.length+1);A()[b>>>2>>>0]=d;return 0}function Ec(a){return E?P(20,1,a):52}function Fc(a,b,c,d){return E?P(21,1,a,b,c,d):52}function Gc(a,b,c,d){return E?P(22,1,a,b,c,d):70}
var xe=[null,[],[]];function Hc(a,b,c,d){if(E)return P(23,1,a,b,c,d);b>>>=0;c>>>=0;d>>>=0;for(var f=0,g=0;g<c;g++){var k=A()[b>>>2>>>0],m=A()[b+4>>>2>>>0];b+=8;for(var p=0;p<m;p++){var n=w()[k+p>>>0],r=xe[a];0===n||10===n?((1===a?Ea:H)(md(r,0)),r.length=0):r.push(n)}f+=m}A()[d>>>2>>>0]=f;return 0}var ye=[31,29,31,30,31,30,31,31,30,31,30,31],ze=[31,28,31,30,31,30,31,31,30,31,30,31];function Ae(a){var b=Array(nd(a)+1);od(a,b,0,b.length);return b}var Be=(a,b)=>{e().set(a,b>>>0)};
function Jc(a,b,c,d){function f(h,u,y){for(h="number"==typeof h?h.toString():h||"";h.length<u;)h=y[0]+h;return h}function g(h,u){return f(h,u,"0")}function k(h,u){function y(Uc){return 0>Uc?-1:0<Uc?1:0}var ba;0===(ba=y(h.getFullYear()-u.getFullYear()))&&0===(ba=y(h.getMonth()-u.getMonth()))&&(ba=y(h.getDate()-u.getDate()));return ba}function m(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function p(h){var u=h.Cb;for(h=new Date((new Date(h.Db+1900,0,1)).getTime());0<u;){var y=h.getMonth(),ba=(me(h.getFullYear())?ye:ze)[y];if(u>ba-h.getDate())u-=ba-h.getDate()+1,h.setDate(1),11>y?h.setMonth(y+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+u);break}}y=new Date(h.getFullYear()+1,0,4);u=m(new Date(h.getFullYear(),
0,4));y=m(y);return 0>=k(u,h)?0>=k(y,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}a>>>=0;b>>>=0;c>>>=0;d>>>=0;var n=A()[d+40>>>2>>>0];d={lc:z()[d>>>2>>>0],kc:z()[d+4>>>2>>>0],Ib:z()[d+8>>>2>>>0],Mb:z()[d+12>>>2>>>0],Jb:z()[d+16>>>2>>>0],Db:z()[d+20>>>2>>>0],vb:z()[d+24>>>2>>>0],Cb:z()[d+28>>>2>>>0],sc:z()[d+32>>>2>>>0],jc:z()[d+36>>>2>>>0],mc:n?L(n):""};c=L(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y",
"%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in n)c=c.replace(new RegExp(r,"g"),n[r]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),x="January February March April May June July August September October November December".split(" ");n={"%a":h=>v[h.vb].substring(0,3),"%A":h=>
v[h.vb],"%b":h=>x[h.Jb].substring(0,3),"%B":h=>x[h.Jb],"%C":h=>g((h.Db+1900)/100|0,2),"%d":h=>g(h.Mb,2),"%e":h=>f(h.Mb,2," "),"%g":h=>p(h).toString().substring(2),"%G":p,"%H":h=>g(h.Ib,2),"%I":h=>{h=h.Ib;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":h=>{for(var u=0,y=0;y<=h.Jb-1;u+=(me(h.Db+1900)?ye:ze)[y++]);return g(h.Mb+u,3)},"%m":h=>g(h.Jb+1,2),"%M":h=>g(h.kc,2),"%n":()=>"\n","%p":h=>0<=h.Ib&&12>h.Ib?"AM":"PM","%S":h=>g(h.lc,2),"%t":()=>"\t","%u":h=>h.vb||7,"%U":h=>g(Math.floor((h.Cb+7-h.vb)/7),
2),"%V":h=>{var u=Math.floor((h.Cb+7-(h.vb+6)%7)/7);2>=(h.vb+371-h.Cb-2)%7&&u++;if(u)53==u&&(y=(h.vb+371-h.Cb)%7,4==y||3==y&&me(h.Db)||(u=1));else{u=52;var y=(h.vb+7-h.Cb-1)%7;(4==y||5==y&&me(h.Db%400-1))&&u++}return g(u,2)},"%w":h=>h.vb,"%W":h=>g(Math.floor((h.Cb+7-(h.vb+6)%7)/7),2),"%y":h=>(h.Db+1900).toString().substring(2),"%Y":h=>h.Db+1900,"%z":h=>{h=h.jc;var u=0<=h;h=Math.abs(h)/60;return(u?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":h=>h.mc,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");
for(r in n)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),n[r](d)));c=c.replace(/\0\0/g,"%");r=Ae(c);if(r.length>b)return 0;Be(r,a);return r.length-1}function Kc(a,b,c,d){return Jc(a>>>0,b>>>0,c>>>0,d>>>0)}E||$c();for(var Ce=Array(256),De=0;256>De;++De)Ce[De]=String.fromCharCode(De);qd=Ce;R=B.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};B.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};U.push(0,1,void 0,1,null,1,!0,1,!1,1);
B.count_emval_handles=()=>U.length/2-5-wd.length;
var Ld=[Ic,Yc,kd,ob,pb,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,lc,mc,Bc,Cc,Ec,Fc,Gc,Hc],jb,Y=function(){function a(c,d){Y=c.exports;Y=Qd();Y=Ee();Zc.push(Y.jb);Ya.unshift(Y.Ca);Ua=d;cb();return Y}var b=Ja();$a++;if(B.instantiateWasm)try{return B.instantiateWasm(b,a)}catch(c){H(`Module.instantiateWasm callback failed with error: ${c}`),oa(c)}eb||=B.locateFile?db("ort-wasm-simd-threaded.jsep.wasm")?"ort-wasm-simd-threaded.jsep.wasm":B.locateFile?B.locateFile("ort-wasm-simd-threaded.jsep.wasm",G):G+"ort-wasm-simd-threaded.jsep.wasm":
(new URL("ort-wasm-simd-threaded.jsep.wasm",import.meta.url)).href;ib(b,function(c){a(c.instance,c.module)}).catch(oa);return{}}(),Md=a=>(Md=Y.Da)(a),Oa=()=>(Oa=Y.Ea)();B._OrtInit=(a,b)=>(B._OrtInit=Y.Fa)(a,b);B._OrtGetLastError=(a,b)=>(B._OrtGetLastError=Y.Ga)(a,b);B._OrtCreateSessionOptions=(a,b,c,d,f,g,k,m,p,n)=>(B._OrtCreateSessionOptions=Y.Ha)(a,b,c,d,f,g,k,m,p,n);B._OrtAppendExecutionProvider=(a,b)=>(B._OrtAppendExecutionProvider=Y.Ia)(a,b);
B._OrtAddFreeDimensionOverride=(a,b,c)=>(B._OrtAddFreeDimensionOverride=Y.Ja)(a,b,c);B._OrtAddSessionConfigEntry=(a,b,c)=>(B._OrtAddSessionConfigEntry=Y.Ka)(a,b,c);B._OrtReleaseSessionOptions=a=>(B._OrtReleaseSessionOptions=Y.La)(a);B._OrtCreateSession=(a,b,c)=>(B._OrtCreateSession=Y.Ma)(a,b,c);B._OrtReleaseSession=a=>(B._OrtReleaseSession=Y.Na)(a);B._OrtGetInputOutputCount=(a,b,c)=>(B._OrtGetInputOutputCount=Y.Oa)(a,b,c);B._OrtGetInputName=(a,b)=>(B._OrtGetInputName=Y.Pa)(a,b);
B._OrtGetOutputName=(a,b)=>(B._OrtGetOutputName=Y.Qa)(a,b);B._OrtFree=a=>(B._OrtFree=Y.Ra)(a);B._OrtCreateTensor=(a,b,c,d,f,g)=>(B._OrtCreateTensor=Y.Sa)(a,b,c,d,f,g);B._OrtGetTensorData=(a,b,c,d,f)=>(B._OrtGetTensorData=Y.Ta)(a,b,c,d,f);B._OrtReleaseTensor=a=>(B._OrtReleaseTensor=Y.Ua)(a);B._OrtCreateRunOptions=(a,b,c,d)=>(B._OrtCreateRunOptions=Y.Va)(a,b,c,d);B._OrtAddRunConfigEntry=(a,b,c)=>(B._OrtAddRunConfigEntry=Y.Wa)(a,b,c);B._OrtReleaseRunOptions=a=>(B._OrtReleaseRunOptions=Y.Xa)(a);
B._OrtCreateBinding=a=>(B._OrtCreateBinding=Y.Ya)(a);B._OrtBindInput=(a,b,c)=>(B._OrtBindInput=Y.Za)(a,b,c);B._OrtBindOutput=(a,b,c,d)=>(B._OrtBindOutput=Y._a)(a,b,c,d);B._OrtClearBoundOutputs=a=>(B._OrtClearBoundOutputs=Y.$a)(a);B._OrtReleaseBinding=a=>(B._OrtReleaseBinding=Y.ab)(a);B._OrtRunWithBinding=(a,b,c,d,f)=>(B._OrtRunWithBinding=Y.bb)(a,b,c,d,f);B._OrtRun=(a,b,c,d,f,g,k,m)=>(B._OrtRun=Y.cb)(a,b,c,d,f,g,k,m);B._OrtEndProfiling=a=>(B._OrtEndProfiling=Y.db)(a);
B._JsepOutput=(a,b,c)=>(B._JsepOutput=Y.eb)(a,b,c);B._JsepGetNodeName=a=>(B._JsepGetNodeName=Y.fb)(a);
var Ia=()=>(Ia=Y.gb)(),X=B._free=a=>(X=B._free=Y.hb)(a),Ad=B._malloc=a=>(Ad=B._malloc=Y.ib)(a),Ka=(a,b,c,d,f,g)=>(Ka=Y.lb)(a,b,c,d,f,g),Sa=()=>(Sa=Y.mb)(),Wc=(a,b,c,d,f)=>(Wc=Y.nb)(a,b,c,d,f),bd=a=>(bd=Y.ob)(a),Qa=a=>(Qa=Y.pb)(a),Jd=()=>(Jd=Y.qb)(),ed=(a,b)=>(ed=Y.rb)(a,b),Xc=a=>(Xc=Y.sb)(a),Vc=a=>(Vc=Y.tb)(a),Tc=()=>(Tc=Y.ub)(),fd=B.dynCall_ii=(a,b)=>(fd=B.dynCall_ii=Y.wb)(a,b),ce=a=>(ce=Y.xb)(a),Sd=()=>(Sd=Y.yb)(),be=a=>(be=Y.zb)(a),de=()=>(de=Y.Ab)();B.___start_em_js=932469;B.___stop_em_js=932715;
function Ee(){var a=Y;a=Object.assign({},a);var b=d=>f=>d(f)>>>0,c=d=>()=>d()>>>0;a.Da=b(a.Da);a.gb=c(a.gb);a.ib=b(a.ib);a.emscripten_main_runtime_thread_id=c(a.emscripten_main_runtime_thread_id);a.tb=b(a.tb);a.ub=c(a.ub);return a}B.stackSave=()=>Tc();B.stackRestore=a=>Xc(a);B.stackAlloc=a=>Vc(a);
B.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":e()[a>>>0]=b;break;case "i8":e()[a>>>0]=b;break;case "i16":ca()[a>>>1>>>0]=b;break;case "i32":z()[a>>>2>>>0]=b;break;case "i64":J[a>>>3]=BigInt(b);break;case "float":ja()[a>>>2>>>0]=b;break;case "double":la()[a>>>3>>>0]=b;break;case "*":A()[a>>>2>>>0]=b;break;default:K(`invalid type for setValue: ${c}`)}};
B.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return e()[a>>>0];case "i8":return e()[a>>>0];case "i16":return ca()[a>>>1>>>0];case "i32":return z()[a>>>2>>>0];case "i64":return J[a>>>3];case "float":return ja()[a>>>2>>>0];case "double":return la()[a>>>3>>>0];case "*":return A()[a>>>2>>>0];default:K(`invalid type for getValue: ${b}`)}};B.UTF8ToString=L;B.stringToUTF8=pd;B.lengthBytesUTF8=nd;var Fe;bb=function Ge(){Fe||He();Fe||(bb=Ge)};
function He(){0<$a||(E?(na(B),E||dd(Ya),startWorker(B)):(dd(Xa),0<$a||Fe||(Fe=!0,B.calledRun=!0,I||(E||dd(Ya),na(B),E||dd(Za)))))}He();"use strict";B.PTR_SIZE=4;moduleRtn=pa;


  return moduleRtn;
}
);
})();
export default ortWasmThreaded;
var isPthread = globalThis.self?.name === 'em-pthread';
var isNode = typeof globalThis.process?.versions?.node == 'string';
if (isNode) isPthread = (await import('worker_threads')).workerData === 'em-pthread';

// When running as a pthread, construct a new instance on startup
isPthread && ortWasmThreaded();
